/*
 * This file is generated by jOOQ.
 */
package dev.feldmann.redstonegang.wire.game.base.addons.both.chat.db;


import dev.feldmann.redstonegang.wire.game.base.addons.both.chat.db.tables.ChatHistory;
import dev.feldmann.redstonegang.wire.game.base.addons.both.chat.db.tables.records.ChatHistoryRecord;

import javax.annotation.Generated;

import org.jooq.Identity;
import org.jooq.UniqueKey;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables of 
 * the <code></code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------

    public static final Identity<ChatHistoryRecord, Long> IDENTITY_CHAT_HISTORY = Identities0.IDENTITY_CHAT_HISTORY;

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<ChatHistoryRecord> KEY_CHAT_HISTORY_PRIMARY = UniqueKeys0.KEY_CHAT_HISTORY_PRIMARY;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Identities0 {
        public static Identity<ChatHistoryRecord, Long> IDENTITY_CHAT_HISTORY = Internal.createIdentity(ChatHistory.CHAT_HISTORY, ChatHistory.CHAT_HISTORY.ID);
    }

    private static class UniqueKeys0 {
        public static final UniqueKey<ChatHistoryRecord> KEY_CHAT_HISTORY_PRIMARY = Internal.createUniqueKey(ChatHistory.CHAT_HISTORY, "KEY_chat_history_PRIMARY", ChatHistory.CHAT_HISTORY.ID);
    }
}
