/*
 * This file is generated by jOOQ.
 */
package dev.feldmann.redstonegang.wire.game.base.addons.both.chat.db;


import dev.feldmann.redstonegang.wire.game.base.addons.both.chat.db.tables.ChatHistory;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in 
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>chat_history</code>.
     */
    public static final ChatHistory CHAT_HISTORY = ChatHistory.CHAT_HISTORY;
}
