/*
 * This file is generated by jOOQ.
 */
package dev.feldmann.redstonegang.wire.game.base.addons.server.notificacoes.db;


import dev.feldmann.redstonegang.wire.game.base.addons.server.notificacoes.db.tables.Notificacoes;

import javax.annotation.Generated;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables of the <code>redstonegang_survival</code> 
 * schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index NOTIFICACOES_PRIMARY = Indexes0.NOTIFICACOES_PRIMARY;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Indexes0 {
        public static Index NOTIFICACOES_PRIMARY = Internal.createIndex("PRIMARY", Notificacoes.NOTIFICACOES, new OrderField[] { Notificacoes.NOTIFICACOES.OWNER, Notificacoes.NOTIFICACOES.TYPE }, true);
    }
}
