/*
 * This file is generated by jOOQ.
 */
package dev.feldmann.redstonegang.wire.game.base.addons.server.notificacoes.db;


import dev.feldmann.redstonegang.wire.game.base.addons.server.notificacoes.db.tables.Notificacoes;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in redstonegang_survival
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>redstonegang_survival.notificacoes</code>.
     */
    public static final Notificacoes NOTIFICACOES = Notificacoes.NOTIFICACOES;
}
