FROM redstonegang-java
#redstonegang-bungee

# Sobreescrevendo os envs
ENV JAVA_JAR_FILE="Redstone-Discord.jar"

ENV DISCORD_USE_REDSTONEGANG_API="1"

# Copiando arquivos do servidor
COPY files/ /server/

