/*
 * This file is generated by jOOQ.
 */
package dev.feldmann.redstonegang.common.db.jooq.redstonegang_common;


import dev.feldmann.redstonegang.common.db.jooq.redstonegang_common.tables.Exceptions;
import dev.feldmann.redstonegang.common.db.jooq.redstonegang_common.tables.Expirations;
import dev.feldmann.redstonegang.common.db.jooq.redstonegang_common.tables.GroupOptions;
import dev.feldmann.redstonegang.common.db.jooq.redstonegang_common.tables.Groups;
import dev.feldmann.redstonegang.common.db.jooq.redstonegang_common.tables.MoedaLogs;
import dev.feldmann.redstonegang.common.db.jooq.redstonegang_common.tables.Permissions;
import dev.feldmann.redstonegang.common.db.jooq.redstonegang_common.tables.PermissionsDesc;
import dev.feldmann.redstonegang.common.db.jooq.redstonegang_common.tables.Punishments;
import dev.feldmann.redstonegang.common.db.jooq.redstonegang_common.tables.PunishmentsReasons;
import dev.feldmann.redstonegang.common.db.jooq.redstonegang_common.tables.PunishmentsReasonsDurations;
import dev.feldmann.redstonegang.common.db.jooq.redstonegang_common.tables.Servers;
import dev.feldmann.redstonegang.common.db.jooq.redstonegang_common.tables.Users;
import dev.feldmann.redstonegang.common.db.jooq.redstonegang_common.tables.records.ExceptionsRecord;
import dev.feldmann.redstonegang.common.db.jooq.redstonegang_common.tables.records.ExpirationsRecord;
import dev.feldmann.redstonegang.common.db.jooq.redstonegang_common.tables.records.GroupOptionsRecord;
import dev.feldmann.redstonegang.common.db.jooq.redstonegang_common.tables.records.GroupsRecord;
import dev.feldmann.redstonegang.common.db.jooq.redstonegang_common.tables.records.MoedaLogsRecord;
import dev.feldmann.redstonegang.common.db.jooq.redstonegang_common.tables.records.PermissionsDescRecord;
import dev.feldmann.redstonegang.common.db.jooq.redstonegang_common.tables.records.PermissionsRecord;
import dev.feldmann.redstonegang.common.db.jooq.redstonegang_common.tables.records.PunishmentsReasonsDurationsRecord;
import dev.feldmann.redstonegang.common.db.jooq.redstonegang_common.tables.records.PunishmentsReasonsRecord;
import dev.feldmann.redstonegang.common.db.jooq.redstonegang_common.tables.records.PunishmentsRecord;
import dev.feldmann.redstonegang.common.db.jooq.redstonegang_common.tables.records.ServersRecord;
import dev.feldmann.redstonegang.common.db.jooq.redstonegang_common.tables.records.UsersRecord;

import javax.annotation.Generated;

import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.UniqueKey;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables of 
 * the <code>redstonegang_common</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------

    public static final Identity<ExceptionsRecord, Long> IDENTITY_EXCEPTIONS = Identities0.IDENTITY_EXCEPTIONS;
    public static final Identity<ExpirationsRecord, Long> IDENTITY_EXPIRATIONS = Identities0.IDENTITY_EXPIRATIONS;
    public static final Identity<GroupsRecord, Integer> IDENTITY_GROUPS = Identities0.IDENTITY_GROUPS;
    public static final Identity<MoedaLogsRecord, Long> IDENTITY_MOEDA_LOGS = Identities0.IDENTITY_MOEDA_LOGS;
    public static final Identity<PermissionsRecord, Integer> IDENTITY_PERMISSIONS = Identities0.IDENTITY_PERMISSIONS;
    public static final Identity<PunishmentsRecord, Integer> IDENTITY_PUNISHMENTS = Identities0.IDENTITY_PUNISHMENTS;
    public static final Identity<PunishmentsReasonsRecord, Integer> IDENTITY_PUNISHMENTS_REASONS = Identities0.IDENTITY_PUNISHMENTS_REASONS;
    public static final Identity<PunishmentsReasonsDurationsRecord, Integer> IDENTITY_PUNISHMENTS_REASONS_DURATIONS = Identities0.IDENTITY_PUNISHMENTS_REASONS_DURATIONS;
    public static final Identity<ServersRecord, Integer> IDENTITY_SERVERS = Identities0.IDENTITY_SERVERS;
    public static final Identity<UsersRecord, Integer> IDENTITY_USERS = Identities0.IDENTITY_USERS;

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<ExceptionsRecord> KEY_EXCEPTIONS_PRIMARY = UniqueKeys0.KEY_EXCEPTIONS_PRIMARY;
    public static final UniqueKey<ExpirationsRecord> KEY_EXPIRATIONS_PRIMARY = UniqueKeys0.KEY_EXPIRATIONS_PRIMARY;
    public static final UniqueKey<GroupsRecord> KEY_GROUPS_PRIMARY = UniqueKeys0.KEY_GROUPS_PRIMARY;
    public static final UniqueKey<GroupsRecord> KEY_GROUPS_NAME = UniqueKeys0.KEY_GROUPS_NAME;
    public static final UniqueKey<GroupsRecord> KEY_GROUPS_DEFAULT = UniqueKeys0.KEY_GROUPS_DEFAULT;
    public static final UniqueKey<GroupOptionsRecord> KEY_GROUP_OPTIONS_PRIMARY = UniqueKeys0.KEY_GROUP_OPTIONS_PRIMARY;
    public static final UniqueKey<MoedaLogsRecord> KEY_MOEDA_LOGS_PRIMARY = UniqueKeys0.KEY_MOEDA_LOGS_PRIMARY;
    public static final UniqueKey<PermissionsRecord> KEY_PERMISSIONS_PRIMARY = UniqueKeys0.KEY_PERMISSIONS_PRIMARY;
    public static final UniqueKey<PermissionsRecord> KEY_PERMISSIONS_PERMISSION = UniqueKeys0.KEY_PERMISSIONS_PERMISSION;
    public static final UniqueKey<PermissionsDescRecord> KEY_PERMISSIONS_DESC_PRIMARY = UniqueKeys0.KEY_PERMISSIONS_DESC_PRIMARY;
    public static final UniqueKey<PunishmentsRecord> KEY_PUNISHMENTS_PRIMARY = UniqueKeys0.KEY_PUNISHMENTS_PRIMARY;
    public static final UniqueKey<PunishmentsReasonsRecord> KEY_PUNISHMENTS_REASONS_PRIMARY = UniqueKeys0.KEY_PUNISHMENTS_REASONS_PRIMARY;
    public static final UniqueKey<PunishmentsReasonsDurationsRecord> KEY_PUNISHMENTS_REASONS_DURATIONS_PRIMARY = UniqueKeys0.KEY_PUNISHMENTS_REASONS_DURATIONS_PRIMARY;
    public static final UniqueKey<ServersRecord> KEY_SERVERS_PRIMARY = UniqueKeys0.KEY_SERVERS_PRIMARY;
    public static final UniqueKey<ServersRecord> KEY_SERVERS_NAME = UniqueKeys0.KEY_SERVERS_NAME;
    public static final UniqueKey<UsersRecord> KEY_USERS_PRIMARY = UniqueKeys0.KEY_USERS_PRIMARY;
    public static final UniqueKey<UsersRecord> KEY_USERS_NAME = UniqueKeys0.KEY_USERS_NAME;
    public static final UniqueKey<UsersRecord> KEY_USERS_ACCOUNT_ID = UniqueKeys0.KEY_USERS_ACCOUNT_ID;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<ExpirationsRecord, UsersRecord> USER_FK = ForeignKeys0.USER_FK;
    public static final ForeignKey<GroupOptionsRecord, GroupsRecord> FK_GROUP = ForeignKeys0.FK_GROUP;
    public static final ForeignKey<PunishmentsRecord, UsersRecord> PUNISHMENTS_IBFK_1 = ForeignKeys0.PUNISHMENTS_IBFK_1;
    public static final ForeignKey<PunishmentsRecord, UsersRecord> PUNISHMENTS_IBFK_2 = ForeignKeys0.PUNISHMENTS_IBFK_2;
    public static final ForeignKey<PunishmentsRecord, UsersRecord> PUNISHMENTS_IBFK_3 = ForeignKeys0.PUNISHMENTS_IBFK_3;
    public static final ForeignKey<PunishmentsRecord, PunishmentsReasonsRecord> PUNISHMENTS_IBFK_4 = ForeignKeys0.PUNISHMENTS_IBFK_4;
    public static final ForeignKey<PunishmentsRecord, PunishmentsReasonsRecord> PUNISHMENTS_IBFK_5 = ForeignKeys0.PUNISHMENTS_IBFK_5;
    public static final ForeignKey<PunishmentsReasonsDurationsRecord, PunishmentsReasonsRecord> PUNISHMENTS_REASONS_DURATIONS_IBFK_1 = ForeignKeys0.PUNISHMENTS_REASONS_DURATIONS_IBFK_1;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Identities0 {
        public static Identity<ExceptionsRecord, Long> IDENTITY_EXCEPTIONS = Internal.createIdentity(Exceptions.EXCEPTIONS, Exceptions.EXCEPTIONS.ID);
        public static Identity<ExpirationsRecord, Long> IDENTITY_EXPIRATIONS = Internal.createIdentity(Expirations.EXPIRATIONS, Expirations.EXPIRATIONS.ID);
        public static Identity<GroupsRecord, Integer> IDENTITY_GROUPS = Internal.createIdentity(Groups.GROUPS, Groups.GROUPS.ID);
        public static Identity<MoedaLogsRecord, Long> IDENTITY_MOEDA_LOGS = Internal.createIdentity(MoedaLogs.MOEDA_LOGS, MoedaLogs.MOEDA_LOGS.ID);
        public static Identity<PermissionsRecord, Integer> IDENTITY_PERMISSIONS = Internal.createIdentity(Permissions.PERMISSIONS, Permissions.PERMISSIONS.ID);
        public static Identity<PunishmentsRecord, Integer> IDENTITY_PUNISHMENTS = Internal.createIdentity(Punishments.PUNISHMENTS, Punishments.PUNISHMENTS.ID);
        public static Identity<PunishmentsReasonsRecord, Integer> IDENTITY_PUNISHMENTS_REASONS = Internal.createIdentity(PunishmentsReasons.PUNISHMENTS_REASONS, PunishmentsReasons.PUNISHMENTS_REASONS.ID);
        public static Identity<PunishmentsReasonsDurationsRecord, Integer> IDENTITY_PUNISHMENTS_REASONS_DURATIONS = Internal.createIdentity(PunishmentsReasonsDurations.PUNISHMENTS_REASONS_DURATIONS, PunishmentsReasonsDurations.PUNISHMENTS_REASONS_DURATIONS.ID);
        public static Identity<ServersRecord, Integer> IDENTITY_SERVERS = Internal.createIdentity(Servers.SERVERS, Servers.SERVERS.ID);
        public static Identity<UsersRecord, Integer> IDENTITY_USERS = Internal.createIdentity(Users.USERS, Users.USERS.ID);
    }

    private static class UniqueKeys0 {
        public static final UniqueKey<ExceptionsRecord> KEY_EXCEPTIONS_PRIMARY = Internal.createUniqueKey(Exceptions.EXCEPTIONS, "KEY_exceptions_PRIMARY", Exceptions.EXCEPTIONS.ID);
        public static final UniqueKey<ExpirationsRecord> KEY_EXPIRATIONS_PRIMARY = Internal.createUniqueKey(Expirations.EXPIRATIONS, "KEY_expirations_PRIMARY", Expirations.EXPIRATIONS.ID);
        public static final UniqueKey<GroupsRecord> KEY_GROUPS_PRIMARY = Internal.createUniqueKey(Groups.GROUPS, "KEY_groups_PRIMARY", Groups.GROUPS.ID);
        public static final UniqueKey<GroupsRecord> KEY_GROUPS_NAME = Internal.createUniqueKey(Groups.GROUPS, "KEY_groups_name", Groups.GROUPS.NAME);
        public static final UniqueKey<GroupsRecord> KEY_GROUPS_DEFAULT = Internal.createUniqueKey(Groups.GROUPS, "KEY_groups_default", Groups.GROUPS.DEFAULT);
        public static final UniqueKey<GroupOptionsRecord> KEY_GROUP_OPTIONS_PRIMARY = Internal.createUniqueKey(GroupOptions.GROUP_OPTIONS, "KEY_group_options_PRIMARY", GroupOptions.GROUP_OPTIONS.GROUP, GroupOptions.GROUP_OPTIONS.KEY);
        public static final UniqueKey<MoedaLogsRecord> KEY_MOEDA_LOGS_PRIMARY = Internal.createUniqueKey(MoedaLogs.MOEDA_LOGS, "KEY_moeda_logs_PRIMARY", MoedaLogs.MOEDA_LOGS.ID);
        public static final UniqueKey<PermissionsRecord> KEY_PERMISSIONS_PRIMARY = Internal.createUniqueKey(Permissions.PERMISSIONS, "KEY_permissions_PRIMARY", Permissions.PERMISSIONS.ID);
        public static final UniqueKey<PermissionsRecord> KEY_PERMISSIONS_PERMISSION = Internal.createUniqueKey(Permissions.PERMISSIONS, "KEY_permissions_permission", Permissions.PERMISSIONS.KEY, Permissions.PERMISSIONS.SERVER, Permissions.PERMISSIONS.OWNER, Permissions.PERMISSIONS.TYPE);
        public static final UniqueKey<PermissionsDescRecord> KEY_PERMISSIONS_DESC_PRIMARY = Internal.createUniqueKey(PermissionsDesc.PERMISSIONS_DESC, "KEY_permissions_desc_PRIMARY", PermissionsDesc.PERMISSIONS_DESC.TYPE, PermissionsDesc.PERMISSIONS_DESC.KEY, PermissionsDesc.PERMISSIONS_DESC.SERVER);
        public static final UniqueKey<PunishmentsRecord> KEY_PUNISHMENTS_PRIMARY = Internal.createUniqueKey(Punishments.PUNISHMENTS, "KEY_punishments_PRIMARY", Punishments.PUNISHMENTS.ID);
        public static final UniqueKey<PunishmentsReasonsRecord> KEY_PUNISHMENTS_REASONS_PRIMARY = Internal.createUniqueKey(PunishmentsReasons.PUNISHMENTS_REASONS, "KEY_punishments_reasons_PRIMARY", PunishmentsReasons.PUNISHMENTS_REASONS.ID);
        public static final UniqueKey<PunishmentsReasonsDurationsRecord> KEY_PUNISHMENTS_REASONS_DURATIONS_PRIMARY = Internal.createUniqueKey(PunishmentsReasonsDurations.PUNISHMENTS_REASONS_DURATIONS, "KEY_punishments_reasons_durations_PRIMARY", PunishmentsReasonsDurations.PUNISHMENTS_REASONS_DURATIONS.ID);
        public static final UniqueKey<ServersRecord> KEY_SERVERS_PRIMARY = Internal.createUniqueKey(Servers.SERVERS, "KEY_servers_PRIMARY", Servers.SERVERS.ID);
        public static final UniqueKey<ServersRecord> KEY_SERVERS_NAME = Internal.createUniqueKey(Servers.SERVERS, "KEY_servers_name", Servers.SERVERS.NAME);
        public static final UniqueKey<UsersRecord> KEY_USERS_PRIMARY = Internal.createUniqueKey(Users.USERS, "KEY_users_PRIMARY", Users.USERS.ID);
        public static final UniqueKey<UsersRecord> KEY_USERS_NAME = Internal.createUniqueKey(Users.USERS, "KEY_users_name", Users.USERS.NAME);
        public static final UniqueKey<UsersRecord> KEY_USERS_ACCOUNT_ID = Internal.createUniqueKey(Users.USERS, "KEY_users_account_id", Users.USERS.ACCOUNT_ID);
    }

    private static class ForeignKeys0 {
        public static final ForeignKey<ExpirationsRecord, UsersRecord> USER_FK = Internal.createForeignKey(Keys.KEY_USERS_PRIMARY, Expirations.EXPIRATIONS, "user_fk", Expirations.EXPIRATIONS.USER_ID);
        public static final ForeignKey<GroupOptionsRecord, GroupsRecord> FK_GROUP = Internal.createForeignKey(Keys.KEY_GROUPS_PRIMARY, GroupOptions.GROUP_OPTIONS, "fk_group", GroupOptions.GROUP_OPTIONS.GROUP);
        public static final ForeignKey<PunishmentsRecord, UsersRecord> PUNISHMENTS_IBFK_1 = Internal.createForeignKey(Keys.KEY_USERS_PRIMARY, Punishments.PUNISHMENTS, "punishments_ibfk_1", Punishments.PUNISHMENTS.USER_ID);
        public static final ForeignKey<PunishmentsRecord, UsersRecord> PUNISHMENTS_IBFK_2 = Internal.createForeignKey(Keys.KEY_USERS_PRIMARY, Punishments.PUNISHMENTS, "punishments_ibfk_2", Punishments.PUNISHMENTS.OP_PUNISHMENT_ID);
        public static final ForeignKey<PunishmentsRecord, UsersRecord> PUNISHMENTS_IBFK_3 = Internal.createForeignKey(Keys.KEY_USERS_PRIMARY, Punishments.PUNISHMENTS, "punishments_ibfk_3", Punishments.PUNISHMENTS.OP_REMOVE_ID);
        public static final ForeignKey<PunishmentsRecord, PunishmentsReasonsRecord> PUNISHMENTS_IBFK_4 = Internal.createForeignKey(Keys.KEY_PUNISHMENTS_REASONS_PRIMARY, Punishments.PUNISHMENTS, "punishments_ibfk_4", Punishments.PUNISHMENTS.PUNISHMENT_REASON_ID);
        public static final ForeignKey<PunishmentsRecord, PunishmentsReasonsRecord> PUNISHMENTS_IBFK_5 = Internal.createForeignKey(Keys.KEY_PUNISHMENTS_REASONS_PRIMARY, Punishments.PUNISHMENTS, "punishments_ibfk_5", Punishments.PUNISHMENTS.REMOVE_REASON_ID);
        public static final ForeignKey<PunishmentsReasonsDurationsRecord, PunishmentsReasonsRecord> PUNISHMENTS_REASONS_DURATIONS_IBFK_1 = Internal.createForeignKey(Keys.KEY_PUNISHMENTS_REASONS_PRIMARY, PunishmentsReasonsDurations.PUNISHMENTS_REASONS_DURATIONS, "punishments_reasons_durations_ibfk_1", PunishmentsReasonsDurations.PUNISHMENTS_REASONS_DURATIONS.PUNISHMENT_REASON_ID);
    }
}
