/*
 * This file is generated by jOOQ.
 */
package dev.feldmann.redstonegang.common.db.jooq.redstonegang_common;


import dev.feldmann.redstonegang.common.db.jooq.redstonegang_common.tables.Exceptions;
import dev.feldmann.redstonegang.common.db.jooq.redstonegang_common.tables.Expirations;
import dev.feldmann.redstonegang.common.db.jooq.redstonegang_common.tables.GroupOptions;
import dev.feldmann.redstonegang.common.db.jooq.redstonegang_common.tables.Groups;
import dev.feldmann.redstonegang.common.db.jooq.redstonegang_common.tables.MoedaLogs;
import dev.feldmann.redstonegang.common.db.jooq.redstonegang_common.tables.Permissions;
import dev.feldmann.redstonegang.common.db.jooq.redstonegang_common.tables.PermissionsDesc;
import dev.feldmann.redstonegang.common.db.jooq.redstonegang_common.tables.Punishments;
import dev.feldmann.redstonegang.common.db.jooq.redstonegang_common.tables.PunishmentsReasons;
import dev.feldmann.redstonegang.common.db.jooq.redstonegang_common.tables.PunishmentsReasonsDurations;
import dev.feldmann.redstonegang.common.db.jooq.redstonegang_common.tables.Servers;
import dev.feldmann.redstonegang.common.db.jooq.redstonegang_common.tables.Users;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in redstonegang_common
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>redstonegang_common.exceptions</code>.
     */
    public static final Exceptions EXCEPTIONS = Exceptions.EXCEPTIONS;

    /**
     * The table <code>redstonegang_common.expirations</code>.
     */
    public static final Expirations EXPIRATIONS = Expirations.EXPIRATIONS;

    /**
     * The table <code>redstonegang_common.groups</code>.
     */
    public static final Groups GROUPS = Groups.GROUPS;

    /**
     * The table <code>redstonegang_common.group_options</code>.
     */
    public static final GroupOptions GROUP_OPTIONS = GroupOptions.GROUP_OPTIONS;

    /**
     * The table <code>redstonegang_common.moeda_logs</code>.
     */
    public static final MoedaLogs MOEDA_LOGS = MoedaLogs.MOEDA_LOGS;

    /**
     * The table <code>redstonegang_common.permissions</code>.
     */
    public static final Permissions PERMISSIONS = Permissions.PERMISSIONS;

    /**
     * The table <code>redstonegang_common.permissions_desc</code>.
     */
    public static final PermissionsDesc PERMISSIONS_DESC = PermissionsDesc.PERMISSIONS_DESC;

    /**
     * The table <code>redstonegang_common.punishments</code>.
     */
    public static final Punishments PUNISHMENTS = Punishments.PUNISHMENTS;

    /**
     * The table <code>redstonegang_common.punishments_reasons</code>.
     */
    public static final PunishmentsReasons PUNISHMENTS_REASONS = PunishmentsReasons.PUNISHMENTS_REASONS;

    /**
     * The table <code>redstonegang_common.punishments_reasons_durations</code>.
     */
    public static final PunishmentsReasonsDurations PUNISHMENTS_REASONS_DURATIONS = PunishmentsReasonsDurations.PUNISHMENTS_REASONS_DURATIONS;

    /**
     * The table <code>redstonegang_common.servers</code>.
     */
    public static final Servers SERVERS = Servers.SERVERS;

    /**
     * The table <code>redstonegang_common.users</code>.
     */
    public static final Users USERS = Users.USERS;
}
