/*
 * This file is generated by jOOQ.
 */
package dev.feldmann.redstonegang.common.db.jooq.redstonegang_app;


import dev.feldmann.redstonegang.common.db.jooq.redstonegang_app.tables.Accounts;
import dev.feldmann.redstonegang.common.db.jooq.redstonegang_app.tables.Skins;

import javax.annotation.Generated;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables of the <code>redstonegang_app</code> 
 * schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index ACCOUNTS_ACCOUNTS_FORUM_ID_UNIQUE = Indexes0.ACCOUNTS_ACCOUNTS_FORUM_ID_UNIQUE;
    public static final Index ACCOUNTS_ACCOUNTS_USERNAME_UNIQUE = Indexes0.ACCOUNTS_ACCOUNTS_USERNAME_UNIQUE;
    public static final Index ACCOUNTS_PRIMARY = Indexes0.ACCOUNTS_PRIMARY;
    public static final Index SKINS_PRIMARY = Indexes0.SKINS_PRIMARY;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Indexes0 {
        public static Index ACCOUNTS_ACCOUNTS_FORUM_ID_UNIQUE = Internal.createIndex("accounts_forum_id_unique", Accounts.ACCOUNTS, new OrderField[] { Accounts.ACCOUNTS.FORUM_ID }, true);
        public static Index ACCOUNTS_ACCOUNTS_USERNAME_UNIQUE = Internal.createIndex("accounts_username_unique", Accounts.ACCOUNTS, new OrderField[] { Accounts.ACCOUNTS.USERNAME }, true);
        public static Index ACCOUNTS_PRIMARY = Internal.createIndex("PRIMARY", Accounts.ACCOUNTS, new OrderField[] { Accounts.ACCOUNTS.ID }, true);
        public static Index SKINS_PRIMARY = Internal.createIndex("PRIMARY", Skins.SKINS, new OrderField[] { Skins.SKINS.ID }, true);
    }
}
