/*
 * This file is generated by jOOQ.
 */
package dev.feldmann.redstonegang.common.db.jooq.redstonegang_app;


import dev.feldmann.redstonegang.common.db.jooq.redstonegang_app.tables.Accounts;
import dev.feldmann.redstonegang.common.db.jooq.redstonegang_app.tables.Skins;
import dev.feldmann.redstonegang.common.db.jooq.redstonegang_app.tables.records.AccountsRecord;
import dev.feldmann.redstonegang.common.db.jooq.redstonegang_app.tables.records.SkinsRecord;

import javax.annotation.Generated;

import org.jooq.Identity;
import org.jooq.UniqueKey;
import org.jooq.impl.Internal;
import org.jooq.types.UInteger;
import org.jooq.types.ULong;


/**
 * A class modelling foreign key relationships and constraints of tables of 
 * the <code>redstonegang_app</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------

    public static final Identity<AccountsRecord, UInteger> IDENTITY_ACCOUNTS = Identities0.IDENTITY_ACCOUNTS;
    public static final Identity<SkinsRecord, ULong> IDENTITY_SKINS = Identities0.IDENTITY_SKINS;

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<AccountsRecord> KEY_ACCOUNTS_PRIMARY = UniqueKeys0.KEY_ACCOUNTS_PRIMARY;
    public static final UniqueKey<AccountsRecord> KEY_ACCOUNTS_ACCOUNTS_USERNAME_UNIQUE = UniqueKeys0.KEY_ACCOUNTS_ACCOUNTS_USERNAME_UNIQUE;
    public static final UniqueKey<AccountsRecord> KEY_ACCOUNTS_ACCOUNTS_FORUM_ID_UNIQUE = UniqueKeys0.KEY_ACCOUNTS_ACCOUNTS_FORUM_ID_UNIQUE;
    public static final UniqueKey<SkinsRecord> KEY_SKINS_PRIMARY = UniqueKeys0.KEY_SKINS_PRIMARY;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Identities0 {
        public static Identity<AccountsRecord, UInteger> IDENTITY_ACCOUNTS = Internal.createIdentity(Accounts.ACCOUNTS, Accounts.ACCOUNTS.ID);
        public static Identity<SkinsRecord, ULong> IDENTITY_SKINS = Internal.createIdentity(Skins.SKINS, Skins.SKINS.ID);
    }

    private static class UniqueKeys0 {
        public static final UniqueKey<AccountsRecord> KEY_ACCOUNTS_PRIMARY = Internal.createUniqueKey(Accounts.ACCOUNTS, "KEY_accounts_PRIMARY", Accounts.ACCOUNTS.ID);
        public static final UniqueKey<AccountsRecord> KEY_ACCOUNTS_ACCOUNTS_USERNAME_UNIQUE = Internal.createUniqueKey(Accounts.ACCOUNTS, "KEY_accounts_accounts_username_unique", Accounts.ACCOUNTS.USERNAME);
        public static final UniqueKey<AccountsRecord> KEY_ACCOUNTS_ACCOUNTS_FORUM_ID_UNIQUE = Internal.createUniqueKey(Accounts.ACCOUNTS, "KEY_accounts_accounts_forum_id_unique", Accounts.ACCOUNTS.FORUM_ID);
        public static final UniqueKey<SkinsRecord> KEY_SKINS_PRIMARY = Internal.createUniqueKey(Skins.SKINS, "KEY_skins_PRIMARY", Skins.SKINS.ID);
    }
}
