/*
 * This file is generated by jOOQ.
 */
package dev.feldmann.redstonegang.common.db.jooq.redstonegang_app;


import dev.feldmann.redstonegang.common.db.jooq.DefaultCatalog;
import dev.feldmann.redstonegang.common.db.jooq.redstonegang_app.tables.Accounts;
import dev.feldmann.redstonegang.common.db.jooq.redstonegang_app.tables.Skins;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RedstonegangApp extends SchemaImpl {

    private static final long serialVersionUID = -1522722789;

    /**
     * The reference instance of <code>redstonegang_app</code>
     */
    public static final RedstonegangApp REDSTONEGANG_APP = new RedstonegangApp();

    /**
     * The table <code>redstonegang_app.accounts</code>.
     */
    public final Accounts ACCOUNTS = Accounts.ACCOUNTS;

    /**
     * The table <code>redstonegang_app.skins</code>.
     */
    public final Skins SKINS = Skins.SKINS;

    /**
     * No further instances allowed
     */
    private RedstonegangApp() {
        super("redstonegang_app", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            Accounts.ACCOUNTS,
            Skins.SKINS);
    }
}
