/*
 * This file is generated by jOOQ.
 */
package dev.feldmann.redstonegang.wire.game.base.database.addons.tables.records;


import dev.feldmann.redstonegang.wire.game.base.database.addons.tables.FloatshopTransactions;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class FloatshopTransactionsRecord extends UpdatableRecordImpl<FloatshopTransactionsRecord> implements Record5<Long, Integer, Timestamp, Timestamp, Integer> {

    private static final long serialVersionUID = -2008663085;

    /**
     * Setter for <code>floatshop_transactions.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>floatshop_transactions.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>floatshop_transactions.item_id</code>.
     */
    public void setItemId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>floatshop_transactions.item_id</code>.
     */
    public Integer getItemId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>floatshop_transactions.date_min</code>.
     */
    public void setDateMin(Timestamp value) {
        set(2, value);
    }

    /**
     * Getter for <code>floatshop_transactions.date_min</code>.
     */
    public Timestamp getDateMin() {
        return (Timestamp) get(2);
    }

    /**
     * Setter for <code>floatshop_transactions.date_max</code>.
     */
    public void setDateMax(Timestamp value) {
        set(3, value);
    }

    /**
     * Getter for <code>floatshop_transactions.date_max</code>.
     */
    public Timestamp getDateMax() {
        return (Timestamp) get(3);
    }

    /**
     * Setter for <code>floatshop_transactions.quantity</code>.
     */
    public void setQuantity(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>floatshop_transactions.quantity</code>.
     */
    public Integer getQuantity() {
        return (Integer) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<Long, Integer, Timestamp, Timestamp, Integer> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<Long, Integer, Timestamp, Timestamp, Integer> valuesRow() {
        return (Row5) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return FloatshopTransactions.FLOATSHOP_TRANSACTIONS.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return FloatshopTransactions.FLOATSHOP_TRANSACTIONS.ITEM_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field3() {
        return FloatshopTransactions.FLOATSHOP_TRANSACTIONS.DATE_MIN;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field4() {
        return FloatshopTransactions.FLOATSHOP_TRANSACTIONS.DATE_MAX;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field5() {
        return FloatshopTransactions.FLOATSHOP_TRANSACTIONS.QUANTITY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component2() {
        return getItemId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component3() {
        return getDateMin();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component4() {
        return getDateMax();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component5() {
        return getQuantity();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getItemId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value3() {
        return getDateMin();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value4() {
        return getDateMax();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value5() {
        return getQuantity();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public FloatshopTransactionsRecord value1(Long value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public FloatshopTransactionsRecord value2(Integer value) {
        setItemId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public FloatshopTransactionsRecord value3(Timestamp value) {
        setDateMin(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public FloatshopTransactionsRecord value4(Timestamp value) {
        setDateMax(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public FloatshopTransactionsRecord value5(Integer value) {
        setQuantity(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public FloatshopTransactionsRecord values(Long value1, Integer value2, Timestamp value3, Timestamp value4, Integer value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached FloatshopTransactionsRecord
     */
    public FloatshopTransactionsRecord() {
        super(FloatshopTransactions.FLOATSHOP_TRANSACTIONS);
    }

    /**
     * Create a detached, initialised FloatshopTransactionsRecord
     */
    public FloatshopTransactionsRecord(Long id, Integer itemId, Timestamp dateMin, Timestamp dateMax, Integer quantity) {
        super(FloatshopTransactions.FLOATSHOP_TRANSACTIONS);

        set(0, id);
        set(1, itemId);
        set(2, dateMin);
        set(3, dateMax);
        set(4, quantity);
    }
}
