/*
 * This file is generated by jOOQ.
 */
package dev.feldmann.redstonegang.wire.game.base.database.addons.tables.records;


import dev.feldmann.redstonegang.wire.game.base.database.addons.tables.FloatshopShops;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class FloatshopShopsRecord extends UpdatableRecordImpl<FloatshopShopsRecord> implements Record4<Integer, String, String, Integer> {

    private static final long serialVersionUID = -1249519516;

    /**
     * Setter for <code>floatshop_shops.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>floatshop_shops.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>floatshop_shops.npc_uuid</code>.
     */
    public void setNpcUuid(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>floatshop_shops.npc_uuid</code>.
     */
    public String getNpcUuid() {
        return (String) get(1);
    }

    /**
     * Setter for <code>floatshop_shops.permission</code>.
     */
    public void setPermission(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>floatshop_shops.permission</code>.
     */
    public String getPermission() {
        return (String) get(2);
    }

    /**
     * Setter for <code>floatshop_shops.linhas</code>.
     */
    public void setLinhas(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>floatshop_shops.linhas</code>.
     */
    public Integer getLinhas() {
        return (Integer) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<Integer, String, String, Integer> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<Integer, String, String, Integer> valuesRow() {
        return (Row4) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return FloatshopShops.FLOATSHOP_SHOPS.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return FloatshopShops.FLOATSHOP_SHOPS.NPC_UUID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return FloatshopShops.FLOATSHOP_SHOPS.PERMISSION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field4() {
        return FloatshopShops.FLOATSHOP_SHOPS.LINHAS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getNpcUuid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getPermission();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component4() {
        return getLinhas();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getNpcUuid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getPermission();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value4() {
        return getLinhas();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public FloatshopShopsRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public FloatshopShopsRecord value2(String value) {
        setNpcUuid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public FloatshopShopsRecord value3(String value) {
        setPermission(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public FloatshopShopsRecord value4(Integer value) {
        setLinhas(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public FloatshopShopsRecord values(Integer value1, String value2, String value3, Integer value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached FloatshopShopsRecord
     */
    public FloatshopShopsRecord() {
        super(FloatshopShops.FLOATSHOP_SHOPS);
    }

    /**
     * Create a detached, initialised FloatshopShopsRecord
     */
    public FloatshopShopsRecord(Integer id, String npcUuid, String permission, Integer linhas) {
        super(FloatshopShops.FLOATSHOP_SHOPS);

        set(0, id);
        set(1, npcUuid);
        set(2, permission);
        set(3, linhas);
    }
}
