/*
 * This file is generated by jOOQ.
 */
package dev.feldmann.redstonegang.wire.game.base.database.addons.tables.records;


import dev.feldmann.redstonegang.wire.game.base.database.addons.tables.MultiserverTpRequests;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MultiserverTpRequestsRecord extends UpdatableRecordImpl<MultiserverTpRequestsRecord> implements Record5<Long, Integer, Integer, Timestamp, Timestamp> {

    private static final long serialVersionUID = 1920075352;

    /**
     * Setter for <code>multiserver_tp_requests.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>multiserver_tp_requests.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>multiserver_tp_requests.requester</code>.
     */
    public void setRequester(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>multiserver_tp_requests.requester</code>.
     */
    public Integer getRequester() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>multiserver_tp_requests.requested</code>.
     */
    public void setRequested(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>multiserver_tp_requests.requested</code>.
     */
    public Integer getRequested() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>multiserver_tp_requests.request_time</code>.
     */
    public void setRequestTime(Timestamp value) {
        set(3, value);
    }

    /**
     * Getter for <code>multiserver_tp_requests.request_time</code>.
     */
    public Timestamp getRequestTime() {
        return (Timestamp) get(3);
    }

    /**
     * Setter for <code>multiserver_tp_requests.request_expire</code>.
     */
    public void setRequestExpire(Timestamp value) {
        set(4, value);
    }

    /**
     * Getter for <code>multiserver_tp_requests.request_expire</code>.
     */
    public Timestamp getRequestExpire() {
        return (Timestamp) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<Long, Integer, Integer, Timestamp, Timestamp> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<Long, Integer, Integer, Timestamp, Timestamp> valuesRow() {
        return (Row5) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return MultiserverTpRequests.MULTISERVER_TP_REQUESTS.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return MultiserverTpRequests.MULTISERVER_TP_REQUESTS.REQUESTER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return MultiserverTpRequests.MULTISERVER_TP_REQUESTS.REQUESTED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field4() {
        return MultiserverTpRequests.MULTISERVER_TP_REQUESTS.REQUEST_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field5() {
        return MultiserverTpRequests.MULTISERVER_TP_REQUESTS.REQUEST_EXPIRE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component2() {
        return getRequester();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component3() {
        return getRequested();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component4() {
        return getRequestTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component5() {
        return getRequestExpire();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getRequester();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getRequested();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value4() {
        return getRequestTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value5() {
        return getRequestExpire();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MultiserverTpRequestsRecord value1(Long value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MultiserverTpRequestsRecord value2(Integer value) {
        setRequester(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MultiserverTpRequestsRecord value3(Integer value) {
        setRequested(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MultiserverTpRequestsRecord value4(Timestamp value) {
        setRequestTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MultiserverTpRequestsRecord value5(Timestamp value) {
        setRequestExpire(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MultiserverTpRequestsRecord values(Long value1, Integer value2, Integer value3, Timestamp value4, Timestamp value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached MultiserverTpRequestsRecord
     */
    public MultiserverTpRequestsRecord() {
        super(MultiserverTpRequests.MULTISERVER_TP_REQUESTS);
    }

    /**
     * Create a detached, initialised MultiserverTpRequestsRecord
     */
    public MultiserverTpRequestsRecord(Long id, Integer requester, Integer requested, Timestamp requestTime, Timestamp requestExpire) {
        super(MultiserverTpRequests.MULTISERVER_TP_REQUESTS);

        set(0, id);
        set(1, requester);
        set(2, requested);
        set(3, requestTime);
        set(4, requestExpire);
    }
}
