/*
 * This file is generated by jOOQ.
 */
package dev.feldmann.redstonegang.wire.game.base.database.addons.tables.records;


import dev.feldmann.redstonegang.wire.game.base.database.addons.tables.Terrenos;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record8;
import org.jooq.Row8;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TerrenosRecord extends UpdatableRecordImpl<TerrenosRecord> implements Record8<Integer, Integer, Integer, Integer, Integer, Integer, String, String> {

    private static final long serialVersionUID = -49150965;

    /**
     * Setter for <code>terrenos.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>terrenos.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>terrenos.owner</code>.
     */
    public void setOwner(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>terrenos.owner</code>.
     */
    public Integer getOwner() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>terrenos.minX</code>.
     */
    public void setMinx(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>terrenos.minX</code>.
     */
    public Integer getMinx() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>terrenos.maxX</code>.
     */
    public void setMaxx(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>terrenos.maxX</code>.
     */
    public Integer getMaxx() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>terrenos.minZ</code>.
     */
    public void setMinz(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>terrenos.minZ</code>.
     */
    public Integer getMinz() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>terrenos.maxZ</code>.
     */
    public void setMaxz(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>terrenos.maxZ</code>.
     */
    public Integer getMaxz() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>terrenos.world</code>.
     */
    public void setWorld(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>terrenos.world</code>.
     */
    public String getWorld() {
        return (String) get(6);
    }

    /**
     * Setter for <code>terrenos.properties</code>.
     */
    public void setProperties(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>terrenos.properties</code>.
     */
    public String getProperties() {
        return (String) get(7);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record8 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row8<Integer, Integer, Integer, Integer, Integer, Integer, String, String> fieldsRow() {
        return (Row8) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row8<Integer, Integer, Integer, Integer, Integer, Integer, String, String> valuesRow() {
        return (Row8) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return Terrenos.TERRENOS.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return Terrenos.TERRENOS.OWNER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return Terrenos.TERRENOS.MINX;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field4() {
        return Terrenos.TERRENOS.MAXX;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field5() {
        return Terrenos.TERRENOS.MINZ;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field6() {
        return Terrenos.TERRENOS.MAXZ;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return Terrenos.TERRENOS.WORLD;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field8() {
        return Terrenos.TERRENOS.PROPERTIES;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component2() {
        return getOwner();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component3() {
        return getMinx();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component4() {
        return getMaxx();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component5() {
        return getMinz();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component6() {
        return getMaxz();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component7() {
        return getWorld();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component8() {
        return getProperties();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getOwner();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getMinx();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value4() {
        return getMaxx();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value5() {
        return getMinz();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value6() {
        return getMaxz();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getWorld();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value8() {
        return getProperties();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TerrenosRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TerrenosRecord value2(Integer value) {
        setOwner(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TerrenosRecord value3(Integer value) {
        setMinx(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TerrenosRecord value4(Integer value) {
        setMaxx(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TerrenosRecord value5(Integer value) {
        setMinz(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TerrenosRecord value6(Integer value) {
        setMaxz(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TerrenosRecord value7(String value) {
        setWorld(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TerrenosRecord value8(String value) {
        setProperties(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TerrenosRecord values(Integer value1, Integer value2, Integer value3, Integer value4, Integer value5, Integer value6, String value7, String value8) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TerrenosRecord
     */
    public TerrenosRecord() {
        super(Terrenos.TERRENOS);
    }

    /**
     * Create a detached, initialised TerrenosRecord
     */
    public TerrenosRecord(Integer id, Integer owner, Integer minx, Integer maxx, Integer minz, Integer maxz, String world, String properties) {
        super(Terrenos.TERRENOS);

        set(0, id);
        set(1, owner);
        set(2, minx);
        set(3, maxx);
        set(4, minz);
        set(5, maxz);
        set(6, world);
        set(7, properties);
    }
}
