/*
 * This file is generated by jOOQ.
 */
package dev.feldmann.redstonegang.common.db.jooq.redstonegang_magento.tables.records;


import dev.feldmann.redstonegang.common.db.jooq.redstonegang_magento.tables.DrmagentoGamecodesCode;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record11;
import org.jooq.Row11;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.types.UInteger;


/**
 * drmagento_gamecodes_code
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DrmagentoGamecodesCodeRecord extends UpdatableRecordImpl<DrmagentoGamecodesCodeRecord> implements Record11<UInteger, String, String, Timestamp, String, Timestamp, Integer, UInteger, UInteger, Byte, Integer> {

    private static final long serialVersionUID = 764558927;

    /**
     * Setter for <code>redstonegang_magento.drmagento_gamecodes_code.code_id</code>. Entity ID
     */
    public void setCodeId(UInteger value) {
        set(0, value);
    }

    /**
     * Getter for <code>redstonegang_magento.drmagento_gamecodes_code.code_id</code>. Entity ID
     */
    public UInteger getCodeId() {
        return (UInteger) get(0);
    }

    /**
     * Setter for <code>redstonegang_magento.drmagento_gamecodes_code.pincode</code>. Pin Code
     */
    public void setPincode(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>redstonegang_magento.drmagento_gamecodes_code.pincode</code>. Pin Code
     */
    public String getPincode() {
        return (String) get(1);
    }

    /**
     * Setter for <code>redstonegang_magento.drmagento_gamecodes_code.type</code>. Type
     */
    public void setType(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>redstonegang_magento.drmagento_gamecodes_code.type</code>. Type
     */
    public String getType() {
        return (String) get(2);
    }

    /**
     * Setter for <code>redstonegang_magento.drmagento_gamecodes_code.date</code>. Date
     */
    public void setDate(Timestamp value) {
        set(3, value);
    }

    /**
     * Getter for <code>redstonegang_magento.drmagento_gamecodes_code.date</code>. Date
     */
    public Timestamp getDate() {
        return (Timestamp) get(3);
    }

    /**
     * Setter for <code>redstonegang_magento.drmagento_gamecodes_code.email</code>. Email
     */
    public void setEmail(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>redstonegang_magento.drmagento_gamecodes_code.email</code>. Email
     */
    public String getEmail() {
        return (String) get(4);
    }

    /**
     * Setter for <code>redstonegang_magento.drmagento_gamecodes_code.activedate</code>. ActiveDate
     */
    public void setActivedate(Timestamp value) {
        set(5, value);
    }

    /**
     * Getter for <code>redstonegang_magento.drmagento_gamecodes_code.activedate</code>. ActiveDate
     */
    public Timestamp getActivedate() {
        return (Timestamp) get(5);
    }

    /**
     * Setter for <code>redstonegang_magento.drmagento_gamecodes_code.user_id</code>. User ID
     */
    public void setUserId(Integer value) {
        set(6, value);
    }

    /**
     * Getter for <code>redstonegang_magento.drmagento_gamecodes_code.user_id</code>. User ID
     */
    public Integer getUserId() {
        return (Integer) get(6);
    }

    /**
     * Setter for <code>redstonegang_magento.drmagento_gamecodes_code.order_id</code>. Order ID
     */
    public void setOrderId(UInteger value) {
        set(7, value);
    }

    /**
     * Getter for <code>redstonegang_magento.drmagento_gamecodes_code.order_id</code>. Order ID
     */
    public UInteger getOrderId() {
        return (UInteger) get(7);
    }

    /**
     * Setter for <code>redstonegang_magento.drmagento_gamecodes_code.item_id</code>. Item ID
     */
    public void setItemId(UInteger value) {
        set(8, value);
    }

    /**
     * Getter for <code>redstonegang_magento.drmagento_gamecodes_code.item_id</code>. Item ID
     */
    public UInteger getItemId() {
        return (UInteger) get(8);
    }

    /**
     * Setter for <code>redstonegang_magento.drmagento_gamecodes_code.lock</code>. Lock
     */
    public void setLock(Byte value) {
        set(9, value);
    }

    /**
     * Getter for <code>redstonegang_magento.drmagento_gamecodes_code.lock</code>. Lock
     */
    public Byte getLock() {
        return (Byte) get(9);
    }

    /**
     * Setter for <code>redstonegang_magento.drmagento_gamecodes_code.type_amount</code>. Type Amount
     */
    public void setTypeAmount(Integer value) {
        set(10, value);
    }

    /**
     * Getter for <code>redstonegang_magento.drmagento_gamecodes_code.type_amount</code>. Type Amount
     */
    public Integer getTypeAmount() {
        return (Integer) get(10);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<UInteger> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record11 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row11<UInteger, String, String, Timestamp, String, Timestamp, Integer, UInteger, UInteger, Byte, Integer> fieldsRow() {
        return (Row11) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row11<UInteger, String, String, Timestamp, String, Timestamp, Integer, UInteger, UInteger, Byte, Integer> valuesRow() {
        return (Row11) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UInteger> field1() {
        return DrmagentoGamecodesCode.DRMAGENTO_GAMECODES_CODE.CODE_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return DrmagentoGamecodesCode.DRMAGENTO_GAMECODES_CODE.PINCODE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return DrmagentoGamecodesCode.DRMAGENTO_GAMECODES_CODE.TYPE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field4() {
        return DrmagentoGamecodesCode.DRMAGENTO_GAMECODES_CODE.DATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return DrmagentoGamecodesCode.DRMAGENTO_GAMECODES_CODE.EMAIL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field6() {
        return DrmagentoGamecodesCode.DRMAGENTO_GAMECODES_CODE.ACTIVEDATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field7() {
        return DrmagentoGamecodesCode.DRMAGENTO_GAMECODES_CODE.USER_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UInteger> field8() {
        return DrmagentoGamecodesCode.DRMAGENTO_GAMECODES_CODE.ORDER_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UInteger> field9() {
        return DrmagentoGamecodesCode.DRMAGENTO_GAMECODES_CODE.ITEM_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Byte> field10() {
        return DrmagentoGamecodesCode.DRMAGENTO_GAMECODES_CODE.LOCK;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field11() {
        return DrmagentoGamecodesCode.DRMAGENTO_GAMECODES_CODE.TYPE_AMOUNT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger component1() {
        return getCodeId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getPincode();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component4() {
        return getDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getEmail();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component6() {
        return getActivedate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component7() {
        return getUserId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger component8() {
        return getOrderId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger component9() {
        return getItemId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte component10() {
        return getLock();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component11() {
        return getTypeAmount();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger value1() {
        return getCodeId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getPincode();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value4() {
        return getDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getEmail();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value6() {
        return getActivedate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value7() {
        return getUserId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger value8() {
        return getOrderId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger value9() {
        return getItemId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte value10() {
        return getLock();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value11() {
        return getTypeAmount();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DrmagentoGamecodesCodeRecord value1(UInteger value) {
        setCodeId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DrmagentoGamecodesCodeRecord value2(String value) {
        setPincode(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DrmagentoGamecodesCodeRecord value3(String value) {
        setType(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DrmagentoGamecodesCodeRecord value4(Timestamp value) {
        setDate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DrmagentoGamecodesCodeRecord value5(String value) {
        setEmail(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DrmagentoGamecodesCodeRecord value6(Timestamp value) {
        setActivedate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DrmagentoGamecodesCodeRecord value7(Integer value) {
        setUserId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DrmagentoGamecodesCodeRecord value8(UInteger value) {
        setOrderId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DrmagentoGamecodesCodeRecord value9(UInteger value) {
        setItemId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DrmagentoGamecodesCodeRecord value10(Byte value) {
        setLock(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DrmagentoGamecodesCodeRecord value11(Integer value) {
        setTypeAmount(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DrmagentoGamecodesCodeRecord values(UInteger value1, String value2, String value3, Timestamp value4, String value5, Timestamp value6, Integer value7, UInteger value8, UInteger value9, Byte value10, Integer value11) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached DrmagentoGamecodesCodeRecord
     */
    public DrmagentoGamecodesCodeRecord() {
        super(DrmagentoGamecodesCode.DRMAGENTO_GAMECODES_CODE);
    }

    /**
     * Create a detached, initialised DrmagentoGamecodesCodeRecord
     */
    public DrmagentoGamecodesCodeRecord(UInteger codeId, String pincode, String type, Timestamp date, String email, Timestamp activedate, Integer userId, UInteger orderId, UInteger itemId, Byte lock, Integer typeAmount) {
        super(DrmagentoGamecodesCode.DRMAGENTO_GAMECODES_CODE);

        set(0, codeId);
        set(1, pincode);
        set(2, type);
        set(3, date);
        set(4, email);
        set(5, activedate);
        set(6, userId);
        set(7, orderId);
        set(8, itemId);
        set(9, lock);
        set(10, typeAmount);
    }
}
