/*
 * This file is generated by jOOQ.
 */
package dev.feldmann.redstonegang.wire.game.base.addonconfigs.db;


import dev.feldmann.redstonegang.wire.game.base.addonconfigs.db.tables.AddonsConfigs;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RedstonegangCommon extends SchemaImpl {

    private static final long serialVersionUID = -1963913041;

    /**
     * The reference redstonegang of <code>redstonegang_common</code>
     */
    public static final RedstonegangCommon REDSTONEGANG_COMMON = new RedstonegangCommon();

    /**
     * The table <code>redstonegang_common.addons_configs</code>.
     */
    public final AddonsConfigs ADDONS_CONFIGS = AddonsConfigs.ADDONS_CONFIGS;

    /**
     * No further instances allowed
     */
    private RedstonegangCommon() {
        super("redstonegang_common", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            AddonsConfigs.ADDONS_CONFIGS);
    }
}
