/*
 * This file is generated by jOOQ.
 */
package dev.feldmann.redstonegang.wire.game.base.addons.both.shop.db;


import dev.feldmann.redstonegang.wire.game.base.addons.both.shop.db.tables.LojaItens;
import dev.feldmann.redstonegang.wire.game.base.addons.both.shop.db.tables.Vencimentos;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DefaultSchema extends SchemaImpl {

    private static final long serialVersionUID = -1821343644;

    /**
     * The reference redstonegang of <code></code>
     */
    public static final DefaultSchema DEFAULT_SCHEMA = new DefaultSchema();

    /**
     * The table <code>loja_itens</code>.
     */
    public final LojaItens LOJA_ITENS = LojaItens.LOJA_ITENS;

    /**
     * The table <code>vencimentos</code>.
     */
    public final Vencimentos VENCIMENTOS = Vencimentos.VENCIMENTOS;

    /**
     * No further instances allowed
     */
    private DefaultSchema() {
        super("", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            LojaItens.LOJA_ITENS,
            Vencimentos.VENCIMENTOS);
    }
}
