/*
 * This file is generated by jOOQ.
 */
package dev.feldmann.redstonegang.wire.game.base.addons.both.shop.db;


import dev.feldmann.redstonegang.wire.game.base.addons.both.shop.db.tables.LojaItens;
import dev.feldmann.redstonegang.wire.game.base.addons.both.shop.db.tables.Vencimentos;
import dev.feldmann.redstonegang.wire.game.base.addons.both.shop.db.tables.records.LojaItensRecord;
import dev.feldmann.redstonegang.wire.game.base.addons.both.shop.db.tables.records.VencimentosRecord;

import javax.annotation.Generated;

import org.jooq.Identity;
import org.jooq.UniqueKey;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables of 
 * the <code></code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------

    public static final Identity<LojaItensRecord, Integer> IDENTITY_LOJA_ITENS = Identities0.IDENTITY_LOJA_ITENS;
    public static final Identity<VencimentosRecord, Integer> IDENTITY_VENCIMENTOS = Identities0.IDENTITY_VENCIMENTOS;

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<LojaItensRecord> KEY_LOJA_ITENS_PRIMARY = UniqueKeys0.KEY_LOJA_ITENS_PRIMARY;
    public static final UniqueKey<VencimentosRecord> KEY_VENCIMENTOS_PRIMARY = UniqueKeys0.KEY_VENCIMENTOS_PRIMARY;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Identities0 {
        public static Identity<LojaItensRecord, Integer> IDENTITY_LOJA_ITENS = Internal.createIdentity(LojaItens.LOJA_ITENS, LojaItens.LOJA_ITENS.ID);
        public static Identity<VencimentosRecord, Integer> IDENTITY_VENCIMENTOS = Internal.createIdentity(Vencimentos.VENCIMENTOS, Vencimentos.VENCIMENTOS.ID);
    }

    private static class UniqueKeys0 {
        public static final UniqueKey<LojaItensRecord> KEY_LOJA_ITENS_PRIMARY = Internal.createUniqueKey(LojaItens.LOJA_ITENS, "KEY_loja_itens_PRIMARY", LojaItens.LOJA_ITENS.ID);
        public static final UniqueKey<VencimentosRecord> KEY_VENCIMENTOS_PRIMARY = Internal.createUniqueKey(Vencimentos.VENCIMENTOS, "KEY_vencimentos_PRIMARY", Vencimentos.VENCIMENTOS.ID);
    }
}
