/*
 * This file is generated by jOOQ.
 */
package dev.feldmann.redstonegang.wire.game.base.addons.both.shop.db;


import dev.feldmann.redstonegang.wire.game.base.addons.both.shop.db.tables.LojaItens;
import dev.feldmann.redstonegang.wire.game.base.addons.both.shop.db.tables.Vencimentos;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in 
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>loja_itens</code>.
     */
    public static final LojaItens LOJA_ITENS = LojaItens.LOJA_ITENS;

    /**
     * The table <code>vencimentos</code>.
     */
    public static final Vencimentos VENCIMENTOS = Vencimentos.VENCIMENTOS;
}
