/*
 * This file is generated by jOOQ.
 */
package dev.feldmann.redstonegang.wire.game.games.servers.survival.addons.ferreiro.db.tables.records;


import dev.feldmann.redstonegang.wire.game.games.servers.survival.addons.ferreiro.db.tables.FerreiroItens;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class FerreiroItensRecord extends UpdatableRecordImpl<FerreiroItensRecord> implements Record6<Long, Integer, byte[], Byte, Timestamp, Timestamp> {

    private static final long serialVersionUID = 223195369;

    /**
     * Setter for <code>redstonegang_survival.ferreiro_itens.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>redstonegang_survival.ferreiro_itens.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>redstonegang_survival.ferreiro_itens.player</code>.
     */
    public void setPlayer(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>redstonegang_survival.ferreiro_itens.player</code>.
     */
    public Integer getPlayer() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>redstonegang_survival.ferreiro_itens.item</code>.
     */
    public void setItem(byte... value) {
        set(2, value);
    }

    /**
     * Getter for <code>redstonegang_survival.ferreiro_itens.item</code>.
     */
    public byte[] getItem() {
        return (byte[]) get(2);
    }

    /**
     * Setter for <code>redstonegang_survival.ferreiro_itens.type</code>.
     */
    public void setType(Byte value) {
        set(3, value);
    }

    /**
     * Getter for <code>redstonegang_survival.ferreiro_itens.type</code>.
     */
    public Byte getType() {
        return (Byte) get(3);
    }

    /**
     * Setter for <code>redstonegang_survival.ferreiro_itens.start</code>.
     */
    public void setStart(Timestamp value) {
        set(4, value);
    }

    /**
     * Getter for <code>redstonegang_survival.ferreiro_itens.start</code>.
     */
    public Timestamp getStart() {
        return (Timestamp) get(4);
    }

    /**
     * Setter for <code>redstonegang_survival.ferreiro_itens.ready</code>.
     */
    public void setReady(Timestamp value) {
        set(5, value);
    }

    /**
     * Getter for <code>redstonegang_survival.ferreiro_itens.ready</code>.
     */
    public Timestamp getReady() {
        return (Timestamp) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<Long, Integer, byte[], Byte, Timestamp, Timestamp> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<Long, Integer, byte[], Byte, Timestamp, Timestamp> valuesRow() {
        return (Row6) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return FerreiroItens.FERREIRO_ITENS.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return FerreiroItens.FERREIRO_ITENS.PLAYER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<byte[]> field3() {
        return FerreiroItens.FERREIRO_ITENS.ITEM;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Byte> field4() {
        return FerreiroItens.FERREIRO_ITENS.TYPE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field5() {
        return FerreiroItens.FERREIRO_ITENS.START;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field6() {
        return FerreiroItens.FERREIRO_ITENS.READY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component2() {
        return getPlayer();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public byte[] component3() {
        return getItem();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte component4() {
        return getType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component5() {
        return getStart();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component6() {
        return getReady();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getPlayer();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public byte[] value3() {
        return getItem();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte value4() {
        return getType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value5() {
        return getStart();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value6() {
        return getReady();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public FerreiroItensRecord value1(Long value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public FerreiroItensRecord value2(Integer value) {
        setPlayer(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public FerreiroItensRecord value3(byte... value) {
        setItem(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public FerreiroItensRecord value4(Byte value) {
        setType(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public FerreiroItensRecord value5(Timestamp value) {
        setStart(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public FerreiroItensRecord value6(Timestamp value) {
        setReady(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public FerreiroItensRecord values(Long value1, Integer value2, byte[] value3, Byte value4, Timestamp value5, Timestamp value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached FerreiroItensRecord
     */
    public FerreiroItensRecord() {
        super(FerreiroItens.FERREIRO_ITENS);
    }

    /**
     * Create a detached, initialised FerreiroItensRecord
     */
    public FerreiroItensRecord(Long id, Integer player, byte[] item, Byte type, Timestamp start, Timestamp ready) {
        super(FerreiroItens.FERREIRO_ITENS);

        set(0, id);
        set(1, player);
        set(2, item);
        set(3, type);
        set(4, start);
        set(5, ready);
    }
}
