/*
 * This file is generated by jOOQ.
 */
package dev.feldmann.redstonegang.common.db.jooq.redstonegang_magento.tables;


import dev.feldmann.redstonegang.common.db.jooq.redstonegang_magento.Indexes;
import dev.feldmann.redstonegang.common.db.jooq.redstonegang_magento.Keys;
import dev.feldmann.redstonegang.common.db.jooq.redstonegang_magento.RedstonegangMagento;
import dev.feldmann.redstonegang.common.db.jooq.redstonegang_magento.tables.records.DrmagentoGamecodesCodeRecord;

import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;
import org.jooq.types.UInteger;


/**
 * drmagento_gamecodes_code
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DrmagentoGamecodesCode extends TableImpl<DrmagentoGamecodesCodeRecord> {

    private static final long serialVersionUID = -1159774270;

    /**
     * The reference instance of <code>redstonegang_magento.drmagento_gamecodes_code</code>
     */
    public static final DrmagentoGamecodesCode DRMAGENTO_GAMECODES_CODE = new DrmagentoGamecodesCode();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<DrmagentoGamecodesCodeRecord> getRecordType() {
        return DrmagentoGamecodesCodeRecord.class;
    }

    /**
     * The column <code>redstonegang_magento.drmagento_gamecodes_code.code_id</code>. Entity ID
     */
    public final TableField<DrmagentoGamecodesCodeRecord, UInteger> CODE_ID = createField("code_id", org.jooq.impl.SQLDataType.INTEGERUNSIGNED.nullable(false).identity(true), this, "Entity ID");

    /**
     * The column <code>redstonegang_magento.drmagento_gamecodes_code.pincode</code>. Pin Code
     */
    public final TableField<DrmagentoGamecodesCodeRecord, String> PINCODE = createField("pincode", org.jooq.impl.SQLDataType.VARCHAR(255).nullable(false), this, "Pin Code");

    /**
     * The column <code>redstonegang_magento.drmagento_gamecodes_code.type</code>. Type
     */
    public final TableField<DrmagentoGamecodesCodeRecord, String> TYPE = createField("type", org.jooq.impl.SQLDataType.VARCHAR(255).nullable(false), this, "Type");

    /**
     * The column <code>redstonegang_magento.drmagento_gamecodes_code.date</code>. Date
     */
    public final TableField<DrmagentoGamecodesCodeRecord, Timestamp> DATE = createField("date", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false).defaultValue(org.jooq.impl.DSL.field("current_timestamp()", org.jooq.impl.SQLDataType.TIMESTAMP)), this, "Date");

    /**
     * The column <code>redstonegang_magento.drmagento_gamecodes_code.email</code>. Email
     */
    public final TableField<DrmagentoGamecodesCodeRecord, String> EMAIL = createField("email", org.jooq.impl.SQLDataType.VARCHAR(255).defaultValue(org.jooq.impl.DSL.inline("NULL", org.jooq.impl.SQLDataType.VARCHAR)), this, "Email");

    /**
     * The column <code>redstonegang_magento.drmagento_gamecodes_code.activedate</code>. ActiveDate
     */
    public final TableField<DrmagentoGamecodesCodeRecord, Timestamp> ACTIVEDATE = createField("activedate", org.jooq.impl.SQLDataType.TIMESTAMP.defaultValue(org.jooq.impl.DSL.inline("NULL", org.jooq.impl.SQLDataType.TIMESTAMP)), this, "ActiveDate");

    /**
     * The column <code>redstonegang_magento.drmagento_gamecodes_code.user_id</code>. User ID
     */
    public final TableField<DrmagentoGamecodesCodeRecord, Integer> USER_ID = createField("user_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "User ID");

    /**
     * The column <code>redstonegang_magento.drmagento_gamecodes_code.order_id</code>. Order ID
     */
    public final TableField<DrmagentoGamecodesCodeRecord, UInteger> ORDER_ID = createField("order_id", org.jooq.impl.SQLDataType.INTEGERUNSIGNED.nullable(false).defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGERUNSIGNED)), this, "Order ID");

    /**
     * The column <code>redstonegang_magento.drmagento_gamecodes_code.item_id</code>. Item ID
     */
    public final TableField<DrmagentoGamecodesCodeRecord, UInteger> ITEM_ID = createField("item_id", org.jooq.impl.SQLDataType.INTEGERUNSIGNED.nullable(false).defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGERUNSIGNED)), this, "Item ID");

    /**
     * The column <code>redstonegang_magento.drmagento_gamecodes_code.lock</code>. Lock
     */
    public final TableField<DrmagentoGamecodesCodeRecord, Byte> LOCK = createField("lock", org.jooq.impl.SQLDataType.TINYINT.nullable(false).defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.TINYINT)), this, "Lock");

    /**
     * The column <code>redstonegang_magento.drmagento_gamecodes_code.type_amount</code>. Type Amount
     */
    public final TableField<DrmagentoGamecodesCodeRecord, Integer> TYPE_AMOUNT = createField("type_amount", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "Type Amount");

    /**
     * Create a <code>redstonegang_magento.drmagento_gamecodes_code</code> table reference
     */
    public DrmagentoGamecodesCode() {
        this(DSL.name("drmagento_gamecodes_code"), null);
    }

    /**
     * Create an aliased <code>redstonegang_magento.drmagento_gamecodes_code</code> table reference
     */
    public DrmagentoGamecodesCode(String alias) {
        this(DSL.name(alias), DRMAGENTO_GAMECODES_CODE);
    }

    /**
     * Create an aliased <code>redstonegang_magento.drmagento_gamecodes_code</code> table reference
     */
    public DrmagentoGamecodesCode(Name alias) {
        this(alias, DRMAGENTO_GAMECODES_CODE);
    }

    private DrmagentoGamecodesCode(Name alias, Table<DrmagentoGamecodesCodeRecord> aliased) {
        this(alias, aliased, null);
    }

    private DrmagentoGamecodesCode(Name alias, Table<DrmagentoGamecodesCodeRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment("drmagento_gamecodes_code"));
    }

    public <O extends Record> DrmagentoGamecodesCode(Table<O> child, ForeignKey<O, DrmagentoGamecodesCodeRecord> key) {
        super(child, key, DRMAGENTO_GAMECODES_CODE);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return RedstonegangMagento.REDSTONEGANG_MAGENTO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.DRMAGENTO_GAMECODES_CODE_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<DrmagentoGamecodesCodeRecord, UInteger> getIdentity() {
        return Keys.IDENTITY_DRMAGENTO_GAMECODES_CODE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<DrmagentoGamecodesCodeRecord> getPrimaryKey() {
        return Keys.KEY_DRMAGENTO_GAMECODES_CODE_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<DrmagentoGamecodesCodeRecord>> getKeys() {
        return Arrays.<UniqueKey<DrmagentoGamecodesCodeRecord>>asList(Keys.KEY_DRMAGENTO_GAMECODES_CODE_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DrmagentoGamecodesCode as(String alias) {
        return new DrmagentoGamecodesCode(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DrmagentoGamecodesCode as(Name alias) {
        return new DrmagentoGamecodesCode(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public DrmagentoGamecodesCode rename(String name) {
        return new DrmagentoGamecodesCode(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public DrmagentoGamecodesCode rename(Name name) {
        return new DrmagentoGamecodesCode(name, null);
    }
}
