/*
 * This file is generated by jOOQ.
 */
package dev.feldmann.redstonegang.common.db.jooq.redstonegang_magento;


import dev.feldmann.redstonegang.common.db.jooq.redstonegang_magento.tables.DrmagentoGamecodesCode;

import javax.annotation.Generated;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables of the <code>redstonegang_magento</code> 
 * schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index DRMAGENTO_GAMECODES_CODE_PRIMARY = Indexes0.DRMAGENTO_GAMECODES_CODE_PRIMARY;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Indexes0 {
        public static Index DRMAGENTO_GAMECODES_CODE_PRIMARY = Internal.createIndex("PRIMARY", DrmagentoGamecodesCode.DRMAGENTO_GAMECODES_CODE, new OrderField[] { DrmagentoGamecodesCode.DRMAGENTO_GAMECODES_CODE.CODE_ID }, true);
    }
}
