/*
 * This file is generated by jOOQ.
 */
package dev.feldmann.redstonegang.common.db.jooq.redstonegang_magento;


import dev.feldmann.redstonegang.common.db.jooq.redstonegang_magento.tables.DrmagentoGamecodesCode;
import dev.feldmann.redstonegang.common.db.jooq.redstonegang_magento.tables.records.DrmagentoGamecodesCodeRecord;

import javax.annotation.Generated;

import org.jooq.Identity;
import org.jooq.UniqueKey;
import org.jooq.impl.Internal;
import org.jooq.types.UInteger;


/**
 * A class modelling foreign key relationships and constraints of tables of 
 * the <code>redstonegang_magento</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------

    public static final Identity<DrmagentoGamecodesCodeRecord, UInteger> IDENTITY_DRMAGENTO_GAMECODES_CODE = Identities0.IDENTITY_DRMAGENTO_GAMECODES_CODE;

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<DrmagentoGamecodesCodeRecord> KEY_DRMAGENTO_GAMECODES_CODE_PRIMARY = UniqueKeys0.KEY_DRMAGENTO_GAMECODES_CODE_PRIMARY;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Identities0 {
        public static Identity<DrmagentoGamecodesCodeRecord, UInteger> IDENTITY_DRMAGENTO_GAMECODES_CODE = Internal.createIdentity(DrmagentoGamecodesCode.DRMAGENTO_GAMECODES_CODE, DrmagentoGamecodesCode.DRMAGENTO_GAMECODES_CODE.CODE_ID);
    }

    private static class UniqueKeys0 {
        public static final UniqueKey<DrmagentoGamecodesCodeRecord> KEY_DRMAGENTO_GAMECODES_CODE_PRIMARY = Internal.createUniqueKey(DrmagentoGamecodesCode.DRMAGENTO_GAMECODES_CODE, "KEY_drmagento_gamecodes_code_PRIMARY", DrmagentoGamecodesCode.DRMAGENTO_GAMECODES_CODE.CODE_ID);
    }
}
