/*
 * This file is generated by jOOQ.
 */
package dev.feldmann.redstonegang.common.db.jooq.redstonegang_magento;


import dev.feldmann.redstonegang.common.db.jooq.DefaultCatalog;
import dev.feldmann.redstonegang.common.db.jooq.redstonegang_magento.tables.DrmagentoGamecodesCode;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RedstonegangMagento extends SchemaImpl {

    private static final long serialVersionUID = 1510589838;

    /**
     * The reference instance of <code>redstonegang_magento</code>
     */
    public static final RedstonegangMagento REDSTONEGANG_MAGENTO = new RedstonegangMagento();

    /**
     * drmagento_gamecodes_code
     */
    public final DrmagentoGamecodesCode DRMAGENTO_GAMECODES_CODE = DrmagentoGamecodesCode.DRMAGENTO_GAMECODES_CODE;

    /**
     * No further instances allowed
     */
    private RedstonegangMagento() {
        super("redstonegang_magento", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            DrmagentoGamecodesCode.DRMAGENTO_GAMECODES_CODE);
    }
}
