/*
 * This file is generated by jOOQ.
 */
package dev.feldmann.redstonegang.common.db.jooq.redstonegang_magento;


import dev.feldmann.redstonegang.common.db.jooq.redstonegang_magento.tables.DrmagentoGamecodesCode;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in redstonegang_magento
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * drmagento_gamecodes_code
     */
    public static final DrmagentoGamecodesCode DRMAGENTO_GAMECODES_CODE = DrmagentoGamecodesCode.DRMAGENTO_GAMECODES_CODE;
}
