/*
 * This file is generated by jOOQ.
 */
package dev.feldmann.redstonegang.common.db.jooq.redstonegang_common.tables.records;


import dev.feldmann.redstonegang.common.db.jooq.redstonegang_common.tables.GroupOptions;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class GroupOptionsRecord extends UpdatableRecordImpl<GroupOptionsRecord> implements Record3<Integer, String, Double> {

    private static final long serialVersionUID = 9117494;

    /**
     * Setter for <code>redstonegang_common.group_options.group</code>.
     */
    public void setGroup(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>redstonegang_common.group_options.group</code>.
     */
    public Integer getGroup() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>redstonegang_common.group_options.key</code>.
     */
    public void setKey(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>redstonegang_common.group_options.key</code>.
     */
    public String getKey() {
        return (String) get(1);
    }

    /**
     * Setter for <code>redstonegang_common.group_options.value</code>.
     */
    public void setValue(Double value) {
        set(2, value);
    }

    /**
     * Getter for <code>redstonegang_common.group_options.value</code>.
     */
    public Double getValue() {
        return (Double) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record2<Integer, String> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<Integer, String, Double> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<Integer, String, Double> valuesRow() {
        return (Row3) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return GroupOptions.GROUP_OPTIONS.GROUP;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return GroupOptions.GROUP_OPTIONS.KEY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Double> field3() {
        return GroupOptions.GROUP_OPTIONS.VALUE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getGroup();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getKey();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double component3() {
        return getValue();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getGroup();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getKey();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double value3() {
        return getValue();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GroupOptionsRecord value1(Integer value) {
        setGroup(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GroupOptionsRecord value2(String value) {
        setKey(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GroupOptionsRecord value3(Double value) {
        setValue(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GroupOptionsRecord values(Integer value1, String value2, Double value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached GroupOptionsRecord
     */
    public GroupOptionsRecord() {
        super(GroupOptions.GROUP_OPTIONS);
    }

    /**
     * Create a detached, initialised GroupOptionsRecord
     */
    public GroupOptionsRecord(Integer group, String key, Double value) {
        super(GroupOptions.GROUP_OPTIONS);

        set(0, group);
        set(1, key);
        set(2, value);
    }
}
