/*
 * This file is generated by jOOQ.
 */
package dev.feldmann.redstonegang.common.db.jooq.redstonegang_common.tables.records;


import dev.feldmann.redstonegang.common.db.jooq.redstonegang_common.tables.Groups;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record10;
import org.jooq.Row10;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class GroupsRecord extends UpdatableRecordImpl<GroupsRecord> implements Record10<Integer, String, String, String, String, Long, Integer, Byte, Integer, Boolean> {

    private static final long serialVersionUID = 781357400;

    /**
     * Setter for <code>redstonegang_common.groups.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>redstonegang_common.groups.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>redstonegang_common.groups.name</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>redstonegang_common.groups.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>redstonegang_common.groups.display_name</code>.
     */
    public void setDisplayName(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>redstonegang_common.groups.display_name</code>.
     */
    public String getDisplayName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>redstonegang_common.groups.prefix</code>.
     */
    public void setPrefix(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>redstonegang_common.groups.prefix</code>.
     */
    public String getPrefix() {
        return (String) get(3);
    }

    /**
     * Setter for <code>redstonegang_common.groups.suffix</code>.
     */
    public void setSuffix(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>redstonegang_common.groups.suffix</code>.
     */
    public String getSuffix() {
        return (String) get(4);
    }

    /**
     * Setter for <code>redstonegang_common.groups.discord_role</code>.
     */
    public void setDiscordRole(Long value) {
        set(5, value);
    }

    /**
     * Getter for <code>redstonegang_common.groups.discord_role</code>.
     */
    public Long getDiscordRole() {
        return (Long) get(5);
    }

    /**
     * Setter for <code>redstonegang_common.groups.forum_group</code>.
     */
    public void setForumGroup(Integer value) {
        set(6, value);
    }

    /**
     * Getter for <code>redstonegang_common.groups.forum_group</code>.
     */
    public Integer getForumGroup() {
        return (Integer) get(6);
    }

    /**
     * Setter for <code>redstonegang_common.groups.forum_mod</code>.
     */
    public void setForumMod(Byte value) {
        set(7, value);
    }

    /**
     * Getter for <code>redstonegang_common.groups.forum_mod</code>.
     */
    public Byte getForumMod() {
        return (Byte) get(7);
    }

    /**
     * Setter for <code>redstonegang_common.groups.parent</code>.
     */
    public void setParent(Integer value) {
        set(8, value);
    }

    /**
     * Getter for <code>redstonegang_common.groups.parent</code>.
     */
    public Integer getParent() {
        return (Integer) get(8);
    }

    /**
     * Setter for <code>redstonegang_common.groups.default</code>.
     */
    public void setDefault(Boolean value) {
        set(9, value);
    }

    /**
     * Getter for <code>redstonegang_common.groups.default</code>.
     */
    public Boolean getDefault() {
        return (Boolean) get(9);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record10 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row10<Integer, String, String, String, String, Long, Integer, Byte, Integer, Boolean> fieldsRow() {
        return (Row10) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row10<Integer, String, String, String, String, Long, Integer, Byte, Integer, Boolean> valuesRow() {
        return (Row10) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return Groups.GROUPS.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Groups.GROUPS.NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return Groups.GROUPS.DISPLAY_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return Groups.GROUPS.PREFIX;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return Groups.GROUPS.SUFFIX;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field6() {
        return Groups.GROUPS.DISCORD_ROLE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field7() {
        return Groups.GROUPS.FORUM_GROUP;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Byte> field8() {
        return Groups.GROUPS.FORUM_MOD;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field9() {
        return Groups.GROUPS.PARENT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field10() {
        return Groups.GROUPS.DEFAULT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getDisplayName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getPrefix();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getSuffix();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component6() {
        return getDiscordRole();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component7() {
        return getForumGroup();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte component8() {
        return getForumMod();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component9() {
        return getParent();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean component10() {
        return getDefault();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getDisplayName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getPrefix();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getSuffix();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value6() {
        return getDiscordRole();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value7() {
        return getForumGroup();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte value8() {
        return getForumMod();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value9() {
        return getParent();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value10() {
        return getDefault();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GroupsRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GroupsRecord value2(String value) {
        setName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GroupsRecord value3(String value) {
        setDisplayName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GroupsRecord value4(String value) {
        setPrefix(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GroupsRecord value5(String value) {
        setSuffix(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GroupsRecord value6(Long value) {
        setDiscordRole(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GroupsRecord value7(Integer value) {
        setForumGroup(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GroupsRecord value8(Byte value) {
        setForumMod(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GroupsRecord value9(Integer value) {
        setParent(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GroupsRecord value10(Boolean value) {
        setDefault(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GroupsRecord values(Integer value1, String value2, String value3, String value4, String value5, Long value6, Integer value7, Byte value8, Integer value9, Boolean value10) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached GroupsRecord
     */
    public GroupsRecord() {
        super(Groups.GROUPS);
    }

    /**
     * Create a detached, initialised GroupsRecord
     */
    public GroupsRecord(Integer id, String name, String displayName, String prefix, String suffix, Long discordRole, Integer forumGroup, Byte forumMod, Integer parent, Boolean default_) {
        super(Groups.GROUPS);

        set(0, id);
        set(1, name);
        set(2, displayName);
        set(3, prefix);
        set(4, suffix);
        set(5, discordRole);
        set(6, forumGroup);
        set(7, forumMod);
        set(8, parent);
        set(9, default_);
    }
}
