/*
 * This file is generated by jOOQ.
 */
package dev.feldmann.redstonegang.common.db.jooq.redstonegang_common.tables.records;


import dev.feldmann.redstonegang.common.db.jooq.redstonegang_common.tables.MoedaLogs;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MoedaLogsRecord extends UpdatableRecordImpl<MoedaLogsRecord> implements Record7<Long, Integer, Integer, String, String, String, Timestamp> {

    private static final long serialVersionUID = -755349472;

    /**
     * Setter for <code>redstonegang_common.moeda_logs.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>redstonegang_common.moeda_logs.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>redstonegang_common.moeda_logs.playerId</code>.
     */
    public void setPlayerid(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>redstonegang_common.moeda_logs.playerId</code>.
     */
    public Integer getPlayerid() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>redstonegang_common.moeda_logs.value</code>.
     */
    public void setValue(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>redstonegang_common.moeda_logs.value</code>.
     */
    public Integer getValue() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>redstonegang_common.moeda_logs.moeda</code>.
     */
    public void setMoeda(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>redstonegang_common.moeda_logs.moeda</code>.
     */
    public String getMoeda() {
        return (String) get(3);
    }

    /**
     * Setter for <code>redstonegang_common.moeda_logs.server</code>.
     */
    public void setServer(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>redstonegang_common.moeda_logs.server</code>.
     */
    public String getServer() {
        return (String) get(4);
    }

    /**
     * Setter for <code>redstonegang_common.moeda_logs.desc</code>.
     */
    public void setDesc(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>redstonegang_common.moeda_logs.desc</code>.
     */
    public String getDesc() {
        return (String) get(5);
    }

    /**
     * Setter for <code>redstonegang_common.moeda_logs.when</code>.
     */
    public void setWhen(Timestamp value) {
        set(6, value);
    }

    /**
     * Getter for <code>redstonegang_common.moeda_logs.when</code>.
     */
    public Timestamp getWhen() {
        return (Timestamp) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<Long, Integer, Integer, String, String, String, Timestamp> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<Long, Integer, Integer, String, String, String, Timestamp> valuesRow() {
        return (Row7) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return MoedaLogs.MOEDA_LOGS.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return MoedaLogs.MOEDA_LOGS.PLAYERID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return MoedaLogs.MOEDA_LOGS.VALUE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return MoedaLogs.MOEDA_LOGS.MOEDA;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return MoedaLogs.MOEDA_LOGS.SERVER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return MoedaLogs.MOEDA_LOGS.DESC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field7() {
        return MoedaLogs.MOEDA_LOGS.WHEN;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component2() {
        return getPlayerid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component3() {
        return getValue();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getMoeda();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getServer();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component6() {
        return getDesc();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component7() {
        return getWhen();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getPlayerid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getValue();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getMoeda();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getServer();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getDesc();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value7() {
        return getWhen();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MoedaLogsRecord value1(Long value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MoedaLogsRecord value2(Integer value) {
        setPlayerid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MoedaLogsRecord value3(Integer value) {
        setValue(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MoedaLogsRecord value4(String value) {
        setMoeda(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MoedaLogsRecord value5(String value) {
        setServer(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MoedaLogsRecord value6(String value) {
        setDesc(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MoedaLogsRecord value7(Timestamp value) {
        setWhen(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MoedaLogsRecord values(Long value1, Integer value2, Integer value3, String value4, String value5, String value6, Timestamp value7) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached MoedaLogsRecord
     */
    public MoedaLogsRecord() {
        super(MoedaLogs.MOEDA_LOGS);
    }

    /**
     * Create a detached, initialised MoedaLogsRecord
     */
    public MoedaLogsRecord(Long id, Integer playerid, Integer value, String moeda, String server, String desc, Timestamp when) {
        super(MoedaLogs.MOEDA_LOGS);

        set(0, id);
        set(1, playerid);
        set(2, value);
        set(3, moeda);
        set(4, server);
        set(5, desc);
        set(6, when);
    }
}
