/*
 * This file is generated by jOOQ.
 */
package dev.feldmann.redstonegang.common.db.jooq.redstonegang_common.tables.records;


import dev.feldmann.redstonegang.common.db.jooq.redstonegang_common.tables.PermissionsDesc;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record3;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PermissionsDescRecord extends UpdatableRecordImpl<PermissionsDescRecord> implements Record5<String, Byte, String, String, String> {

    private static final long serialVersionUID = 905636074;

    /**
     * Setter for <code>redstonegang_common.permissions_desc.key</code>.
     */
    public void setKey(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>redstonegang_common.permissions_desc.key</code>.
     */
    public String getKey() {
        return (String) get(0);
    }

    /**
     * Setter for <code>redstonegang_common.permissions_desc.type</code>.
     */
    public void setType(Byte value) {
        set(1, value);
    }

    /**
     * Getter for <code>redstonegang_common.permissions_desc.type</code>.
     */
    public Byte getType() {
        return (Byte) get(1);
    }

    /**
     * Setter for <code>redstonegang_common.permissions_desc.name</code>.
     */
    public void setName(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>redstonegang_common.permissions_desc.name</code>.
     */
    public String getName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>redstonegang_common.permissions_desc.desc</code>.
     */
    public void setDesc(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>redstonegang_common.permissions_desc.desc</code>.
     */
    public String getDesc() {
        return (String) get(3);
    }

    /**
     * Setter for <code>redstonegang_common.permissions_desc.server</code>.
     */
    public void setServer(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>redstonegang_common.permissions_desc.server</code>.
     */
    public String getServer() {
        return (String) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record3<Byte, String, String> key() {
        return (Record3) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<String, Byte, String, String, String> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<String, Byte, String, String, String> valuesRow() {
        return (Row5) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return PermissionsDesc.PERMISSIONS_DESC.KEY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Byte> field2() {
        return PermissionsDesc.PERMISSIONS_DESC.TYPE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return PermissionsDesc.PERMISSIONS_DESC.NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return PermissionsDesc.PERMISSIONS_DESC.DESC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return PermissionsDesc.PERMISSIONS_DESC.SERVER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component1() {
        return getKey();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte component2() {
        return getType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getDesc();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getServer();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getKey();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte value2() {
        return getType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getDesc();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getServer();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PermissionsDescRecord value1(String value) {
        setKey(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PermissionsDescRecord value2(Byte value) {
        setType(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PermissionsDescRecord value3(String value) {
        setName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PermissionsDescRecord value4(String value) {
        setDesc(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PermissionsDescRecord value5(String value) {
        setServer(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PermissionsDescRecord values(String value1, Byte value2, String value3, String value4, String value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached PermissionsDescRecord
     */
    public PermissionsDescRecord() {
        super(PermissionsDesc.PERMISSIONS_DESC);
    }

    /**
     * Create a detached, initialised PermissionsDescRecord
     */
    public PermissionsDescRecord(String key, Byte type, String name, String desc, String server) {
        super(PermissionsDesc.PERMISSIONS_DESC);

        set(0, key);
        set(1, type);
        set(2, name);
        set(3, desc);
        set(4, server);
    }
}
