/*
 * This file is generated by jOOQ.
 */
package dev.feldmann.redstonegang.common.db.jooq.redstonegang_common.tables.records;


import dev.feldmann.redstonegang.common.db.jooq.redstonegang_common.tables.PunishmentsReasonsDurations;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PunishmentsReasonsDurationsRecord extends UpdatableRecordImpl<PunishmentsReasonsDurationsRecord> implements Record4<Integer, Integer, Integer, Integer> {

    private static final long serialVersionUID = -9842726;

    /**
     * Setter for <code>redstonegang_common.punishments_reasons_durations.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>redstonegang_common.punishments_reasons_durations.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>redstonegang_common.punishments_reasons_durations.punishment_reason_id</code>.
     */
    public void setPunishmentReasonId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>redstonegang_common.punishments_reasons_durations.punishment_reason_id</code>.
     */
    public Integer getPunishmentReasonId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>redstonegang_common.punishments_reasons_durations.in_order</code>.
     */
    public void setInOrder(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>redstonegang_common.punishments_reasons_durations.in_order</code>.
     */
    public Integer getInOrder() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>redstonegang_common.punishments_reasons_durations.duration</code>.
     */
    public void setDuration(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>redstonegang_common.punishments_reasons_durations.duration</code>.
     */
    public Integer getDuration() {
        return (Integer) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<Integer, Integer, Integer, Integer> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<Integer, Integer, Integer, Integer> valuesRow() {
        return (Row4) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return PunishmentsReasonsDurations.PUNISHMENTS_REASONS_DURATIONS.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return PunishmentsReasonsDurations.PUNISHMENTS_REASONS_DURATIONS.PUNISHMENT_REASON_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return PunishmentsReasonsDurations.PUNISHMENTS_REASONS_DURATIONS.IN_ORDER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field4() {
        return PunishmentsReasonsDurations.PUNISHMENTS_REASONS_DURATIONS.DURATION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component2() {
        return getPunishmentReasonId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component3() {
        return getInOrder();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component4() {
        return getDuration();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getPunishmentReasonId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getInOrder();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value4() {
        return getDuration();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PunishmentsReasonsDurationsRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PunishmentsReasonsDurationsRecord value2(Integer value) {
        setPunishmentReasonId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PunishmentsReasonsDurationsRecord value3(Integer value) {
        setInOrder(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PunishmentsReasonsDurationsRecord value4(Integer value) {
        setDuration(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PunishmentsReasonsDurationsRecord values(Integer value1, Integer value2, Integer value3, Integer value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached PunishmentsReasonsDurationsRecord
     */
    public PunishmentsReasonsDurationsRecord() {
        super(PunishmentsReasonsDurations.PUNISHMENTS_REASONS_DURATIONS);
    }

    /**
     * Create a detached, initialised PunishmentsReasonsDurationsRecord
     */
    public PunishmentsReasonsDurationsRecord(Integer id, Integer punishmentReasonId, Integer inOrder, Integer duration) {
        super(PunishmentsReasonsDurations.PUNISHMENTS_REASONS_DURATIONS);

        set(0, id);
        set(1, punishmentReasonId);
        set(2, inOrder);
        set(3, duration);
    }
}
