/*
 * This file is generated by jOOQ.
 */
package dev.feldmann.redstonegang.common.db.jooq.redstonegang_common.tables.records;


import dev.feldmann.redstonegang.common.db.jooq.redstonegang_common.tables.Users;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record15;
import org.jooq.Row15;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UsersRecord extends UpdatableRecordImpl<UsersRecord> implements Record15<Integer, String, String, Integer, Integer, Timestamp, Integer, Timestamp, String, String, String, String, String, Timestamp, String> {

    private static final long serialVersionUID = 1454125678;

    /**
     * Setter for <code>redstonegang_common.users.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>redstonegang_common.users.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>redstonegang_common.users.name</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>redstonegang_common.users.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>redstonegang_common.users.uuid</code>.
     */
    public void setUuid(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>redstonegang_common.users.uuid</code>.
     */
    public String getUuid() {
        return (String) get(2);
    }

    /**
     * Setter for <code>redstonegang_common.users.account_id</code>.
     */
    public void setAccountId(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>redstonegang_common.users.account_id</code>.
     */
    public Integer getAccountId() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>redstonegang_common.users.group</code>.
     */
    public void setGroup(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>redstonegang_common.users.group</code>.
     */
    public Integer getGroup() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>redstonegang_common.users.registred</code>.
     */
    public void setRegistred(Timestamp value) {
        set(5, value);
    }

    /**
     * Getter for <code>redstonegang_common.users.registred</code>.
     */
    public Timestamp getRegistred() {
        return (Timestamp) get(5);
    }

    /**
     * Setter for <code>redstonegang_common.users.cash</code>.
     */
    public void setCash(Integer value) {
        set(6, value);
    }

    /**
     * Getter for <code>redstonegang_common.users.cash</code>.
     */
    public Integer getCash() {
        return (Integer) get(6);
    }

    /**
     * Setter for <code>redstonegang_common.users.last_cash_claim</code>.
     */
    public void setLastCashClaim(Timestamp value) {
        set(7, value);
    }

    /**
     * Getter for <code>redstonegang_common.users.last_cash_claim</code>.
     */
    public Timestamp getLastCashClaim() {
        return (Timestamp) get(7);
    }

    /**
     * Setter for <code>redstonegang_common.users.server</code>.
     */
    public void setServer(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>redstonegang_common.users.server</code>.
     */
    public String getServer() {
        return (String) get(8);
    }

    /**
     * Setter for <code>redstonegang_common.users.last_server</code>.
     */
    public void setLastServer(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>redstonegang_common.users.last_server</code>.
     */
    public String getLastServer() {
        return (String) get(9);
    }

    /**
     * Setter for <code>redstonegang_common.users.ip</code>.
     */
    public void setIp(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>redstonegang_common.users.ip</code>.
     */
    public String getIp() {
        return (String) get(10);
    }

    /**
     * Setter for <code>redstonegang_common.users.server_identifier</code>.
     */
    public void setServerIdentifier(String value) {
        set(11, value);
    }

    /**
     * Getter for <code>redstonegang_common.users.server_identifier</code>.
     */
    public String getServerIdentifier() {
        return (String) get(11);
    }

    /**
     * Setter for <code>redstonegang_common.users.bungee</code>.
     */
    public void setBungee(String value) {
        set(12, value);
    }

    /**
     * Getter for <code>redstonegang_common.users.bungee</code>.
     */
    public String getBungee() {
        return (String) get(12);
    }

    /**
     * Setter for <code>redstonegang_common.users.last_login</code>.
     */
    public void setLastLogin(Timestamp value) {
        set(13, value);
    }

    /**
     * Getter for <code>redstonegang_common.users.last_login</code>.
     */
    public Timestamp getLastLogin() {
        return (Timestamp) get(13);
    }

    /**
     * Setter for <code>redstonegang_common.users.disguise_name</code>.
     */
    public void setDisguiseName(String value) {
        set(14, value);
    }

    /**
     * Getter for <code>redstonegang_common.users.disguise_name</code>.
     */
    public String getDisguiseName() {
        return (String) get(14);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record15 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row15<Integer, String, String, Integer, Integer, Timestamp, Integer, Timestamp, String, String, String, String, String, Timestamp, String> fieldsRow() {
        return (Row15) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row15<Integer, String, String, Integer, Integer, Timestamp, Integer, Timestamp, String, String, String, String, String, Timestamp, String> valuesRow() {
        return (Row15) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return Users.USERS.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Users.USERS.NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return Users.USERS.UUID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field4() {
        return Users.USERS.ACCOUNT_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field5() {
        return Users.USERS.GROUP;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field6() {
        return Users.USERS.REGISTRED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field7() {
        return Users.USERS.CASH;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field8() {
        return Users.USERS.LAST_CASH_CLAIM;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field9() {
        return Users.USERS.SERVER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field10() {
        return Users.USERS.LAST_SERVER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field11() {
        return Users.USERS.IP;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field12() {
        return Users.USERS.SERVER_IDENTIFIER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field13() {
        return Users.USERS.BUNGEE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field14() {
        return Users.USERS.LAST_LOGIN;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field15() {
        return Users.USERS.DISGUISE_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getUuid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component4() {
        return getAccountId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component5() {
        return getGroup();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component6() {
        return getRegistred();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component7() {
        return getCash();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component8() {
        return getLastCashClaim();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component9() {
        return getServer();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component10() {
        return getLastServer();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component11() {
        return getIp();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component12() {
        return getServerIdentifier();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component13() {
        return getBungee();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component14() {
        return getLastLogin();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component15() {
        return getDisguiseName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getUuid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value4() {
        return getAccountId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value5() {
        return getGroup();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value6() {
        return getRegistred();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value7() {
        return getCash();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value8() {
        return getLastCashClaim();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value9() {
        return getServer();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value10() {
        return getLastServer();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value11() {
        return getIp();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value12() {
        return getServerIdentifier();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value13() {
        return getBungee();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value14() {
        return getLastLogin();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value15() {
        return getDisguiseName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UsersRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UsersRecord value2(String value) {
        setName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UsersRecord value3(String value) {
        setUuid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UsersRecord value4(Integer value) {
        setAccountId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UsersRecord value5(Integer value) {
        setGroup(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UsersRecord value6(Timestamp value) {
        setRegistred(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UsersRecord value7(Integer value) {
        setCash(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UsersRecord value8(Timestamp value) {
        setLastCashClaim(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UsersRecord value9(String value) {
        setServer(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UsersRecord value10(String value) {
        setLastServer(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UsersRecord value11(String value) {
        setIp(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UsersRecord value12(String value) {
        setServerIdentifier(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UsersRecord value13(String value) {
        setBungee(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UsersRecord value14(Timestamp value) {
        setLastLogin(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UsersRecord value15(String value) {
        setDisguiseName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UsersRecord values(Integer value1, String value2, String value3, Integer value4, Integer value5, Timestamp value6, Integer value7, Timestamp value8, String value9, String value10, String value11, String value12, String value13, Timestamp value14, String value15) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        value15(value15);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached UsersRecord
     */
    public UsersRecord() {
        super(Users.USERS);
    }

    /**
     * Create a detached, initialised UsersRecord
     */
    public UsersRecord(Integer id, String name, String uuid, Integer accountId, Integer group, Timestamp registred, Integer cash, Timestamp lastCashClaim, String server, String lastServer, String ip, String serverIdentifier, String bungee, Timestamp lastLogin, String disguiseName) {
        super(Users.USERS);

        set(0, id);
        set(1, name);
        set(2, uuid);
        set(3, accountId);
        set(4, group);
        set(5, registred);
        set(6, cash);
        set(7, lastCashClaim);
        set(8, server);
        set(9, lastServer);
        set(10, ip);
        set(11, serverIdentifier);
        set(12, bungee);
        set(13, lastLogin);
        set(14, disguiseName);
    }
}
