/*
 * This file is generated by jOOQ.
 */
package dev.feldmann.redstonegang.wire.game.base.addons.both.shop.db.tables.records;


import dev.feldmann.redstonegang.wire.game.base.addons.both.shop.db.tables.Vencimentos;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class VencimentosRecord extends UpdatableRecordImpl<VencimentosRecord> implements Record5<Integer, Integer, Integer, Timestamp, Integer> {

    private static final long serialVersionUID = -1968244445;

    /**
     * Setter for <code>vencimentos.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>vencimentos.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>vencimentos.player</code>.
     */
    public void setPlayer(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>vencimentos.player</code>.
     */
    public Integer getPlayer() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>vencimentos.grupo</code>.
     */
    public void setGrupo(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>vencimentos.grupo</code>.
     */
    public Integer getGrupo() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>vencimentos.start</code>.
     */
    public void setStart(Timestamp value) {
        set(3, value);
    }

    /**
     * Getter for <code>vencimentos.start</code>.
     */
    public Timestamp getStart() {
        return (Timestamp) get(3);
    }

    /**
     * Setter for <code>vencimentos.dias</code>.
     */
    public void setDias(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>vencimentos.dias</code>.
     */
    public Integer getDias() {
        return (Integer) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<Integer, Integer, Integer, Timestamp, Integer> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<Integer, Integer, Integer, Timestamp, Integer> valuesRow() {
        return (Row5) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return Vencimentos.VENCIMENTOS.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return Vencimentos.VENCIMENTOS.PLAYER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return Vencimentos.VENCIMENTOS.GRUPO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field4() {
        return Vencimentos.VENCIMENTOS.START;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field5() {
        return Vencimentos.VENCIMENTOS.DIAS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component2() {
        return getPlayer();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component3() {
        return getGrupo();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component4() {
        return getStart();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component5() {
        return getDias();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getPlayer();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getGrupo();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value4() {
        return getStart();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value5() {
        return getDias();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VencimentosRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VencimentosRecord value2(Integer value) {
        setPlayer(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VencimentosRecord value3(Integer value) {
        setGrupo(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VencimentosRecord value4(Timestamp value) {
        setStart(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VencimentosRecord value5(Integer value) {
        setDias(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VencimentosRecord values(Integer value1, Integer value2, Integer value3, Timestamp value4, Integer value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached VencimentosRecord
     */
    public VencimentosRecord() {
        super(Vencimentos.VENCIMENTOS);
    }

    /**
     * Create a detached, initialised VencimentosRecord
     */
    public VencimentosRecord(Integer id, Integer player, Integer grupo, Timestamp start, Integer dias) {
        super(Vencimentos.VENCIMENTOS);

        set(0, id);
        set(1, player);
        set(2, grupo);
        set(3, start);
        set(4, dias);
    }
}
