/*
 * This file is generated by jOOQ.
 */
package dev.feldmann.redstonegang.wire.game.base.database.addons;


import dev.feldmann.redstonegang.wire.game.base.database.addons.tables.FloatshopItems;
import dev.feldmann.redstonegang.wire.game.base.database.addons.tables.FloatshopShops;
import dev.feldmann.redstonegang.wire.game.base.database.addons.tables.FloatshopTransactions;
import dev.feldmann.redstonegang.wire.game.base.database.addons.tables.MultiserverTpRequests;
import dev.feldmann.redstonegang.wire.game.base.database.addons.tables.MultiserverTpTeleports;
import dev.feldmann.redstonegang.wire.game.base.database.addons.tables.PlayerInventories;
import dev.feldmann.redstonegang.wire.game.base.database.addons.tables.Safetime;
import dev.feldmann.redstonegang.wire.game.base.database.addons.tables.SimplecmdsLocations;
import dev.feldmann.redstonegang.wire.game.base.database.addons.tables.SimplecmdsWarps;
import dev.feldmann.redstonegang.wire.game.base.database.addons.tables.Terrenos;
import dev.feldmann.redstonegang.wire.game.base.database.addons.tables.TerrenosPlayers;
import dev.feldmann.redstonegang.wire.game.base.database.addons.tables.Whitelistcmd;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DefaultSchema extends SchemaImpl {

    private static final long serialVersionUID = 1472777202;

    /**
     * The reference instance of <code></code>
     */
    public static final DefaultSchema DEFAULT_SCHEMA = new DefaultSchema();

    /**
     * The table <code>floatshop_items</code>.
     */
    public final FloatshopItems FLOATSHOP_ITEMS = FloatshopItems.FLOATSHOP_ITEMS;

    /**
     * The table <code>floatshop_shops</code>.
     */
    public final FloatshopShops FLOATSHOP_SHOPS = FloatshopShops.FLOATSHOP_SHOPS;

    /**
     * The table <code>floatshop_transactions</code>.
     */
    public final FloatshopTransactions FLOATSHOP_TRANSACTIONS = FloatshopTransactions.FLOATSHOP_TRANSACTIONS;

    /**
     * The table <code>multiserver_tp_requests</code>.
     */
    public final MultiserverTpRequests MULTISERVER_TP_REQUESTS = MultiserverTpRequests.MULTISERVER_TP_REQUESTS;

    /**
     * The table <code>multiserver_tp_teleports</code>.
     */
    public final MultiserverTpTeleports MULTISERVER_TP_TELEPORTS = MultiserverTpTeleports.MULTISERVER_TP_TELEPORTS;

    /**
     * The table <code>player_inventories</code>.
     */
    public final PlayerInventories PLAYER_INVENTORIES = PlayerInventories.PLAYER_INVENTORIES;

    /**
     * The table <code>safetime</code>.
     */
    public final Safetime SAFETIME = Safetime.SAFETIME;

    /**
     * The table <code>simplecmds_locations</code>.
     */
    public final SimplecmdsLocations SIMPLECMDS_LOCATIONS = SimplecmdsLocations.SIMPLECMDS_LOCATIONS;

    /**
     * The table <code>simplecmds_warps</code>.
     */
    public final SimplecmdsWarps SIMPLECMDS_WARPS = SimplecmdsWarps.SIMPLECMDS_WARPS;

    /**
     * The table <code>terrenos</code>.
     */
    public final Terrenos TERRENOS = Terrenos.TERRENOS;

    /**
     * The table <code>terrenos_players</code>.
     */
    public final TerrenosPlayers TERRENOS_PLAYERS = TerrenosPlayers.TERRENOS_PLAYERS;

    /**
     * The table <code>whitelistcmd</code>.
     */
    public final Whitelistcmd WHITELISTCMD = Whitelistcmd.WHITELISTCMD;

    /**
     * No further instances allowed
     */
    private DefaultSchema() {
        super("", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            FloatshopItems.FLOATSHOP_ITEMS,
            FloatshopShops.FLOATSHOP_SHOPS,
            FloatshopTransactions.FLOATSHOP_TRANSACTIONS,
            MultiserverTpRequests.MULTISERVER_TP_REQUESTS,
            MultiserverTpTeleports.MULTISERVER_TP_TELEPORTS,
            PlayerInventories.PLAYER_INVENTORIES,
            Safetime.SAFETIME,
            SimplecmdsLocations.SIMPLECMDS_LOCATIONS,
            SimplecmdsWarps.SIMPLECMDS_WARPS,
            Terrenos.TERRENOS,
            TerrenosPlayers.TERRENOS_PLAYERS,
            Whitelistcmd.WHITELISTCMD);
    }
}
