/*
 * This file is generated by jOOQ.
 */
package dev.feldmann.redstonegang.wire.game.base.database.addons;


import dev.feldmann.redstonegang.wire.game.base.database.addons.tables.FloatshopItems;
import dev.feldmann.redstonegang.wire.game.base.database.addons.tables.FloatshopShops;
import dev.feldmann.redstonegang.wire.game.base.database.addons.tables.FloatshopTransactions;
import dev.feldmann.redstonegang.wire.game.base.database.addons.tables.MultiserverTpRequests;
import dev.feldmann.redstonegang.wire.game.base.database.addons.tables.MultiserverTpTeleports;
import dev.feldmann.redstonegang.wire.game.base.database.addons.tables.PlayerInventories;
import dev.feldmann.redstonegang.wire.game.base.database.addons.tables.Safetime;
import dev.feldmann.redstonegang.wire.game.base.database.addons.tables.SimplecmdsLocations;
import dev.feldmann.redstonegang.wire.game.base.database.addons.tables.SimplecmdsWarps;
import dev.feldmann.redstonegang.wire.game.base.database.addons.tables.Terrenos;
import dev.feldmann.redstonegang.wire.game.base.database.addons.tables.TerrenosPlayers;
import dev.feldmann.redstonegang.wire.game.base.database.addons.tables.Whitelistcmd;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in 
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>floatshop_items</code>.
     */
    public static final FloatshopItems FLOATSHOP_ITEMS = FloatshopItems.FLOATSHOP_ITEMS;

    /**
     * The table <code>floatshop_shops</code>.
     */
    public static final FloatshopShops FLOATSHOP_SHOPS = FloatshopShops.FLOATSHOP_SHOPS;

    /**
     * The table <code>floatshop_transactions</code>.
     */
    public static final FloatshopTransactions FLOATSHOP_TRANSACTIONS = FloatshopTransactions.FLOATSHOP_TRANSACTIONS;

    /**
     * The table <code>multiserver_tp_requests</code>.
     */
    public static final MultiserverTpRequests MULTISERVER_TP_REQUESTS = MultiserverTpRequests.MULTISERVER_TP_REQUESTS;

    /**
     * The table <code>multiserver_tp_teleports</code>.
     */
    public static final MultiserverTpTeleports MULTISERVER_TP_TELEPORTS = MultiserverTpTeleports.MULTISERVER_TP_TELEPORTS;

    /**
     * The table <code>player_inventories</code>.
     */
    public static final PlayerInventories PLAYER_INVENTORIES = PlayerInventories.PLAYER_INVENTORIES;

    /**
     * The table <code>safetime</code>.
     */
    public static final Safetime SAFETIME = Safetime.SAFETIME;

    /**
     * The table <code>simplecmds_locations</code>.
     */
    public static final SimplecmdsLocations SIMPLECMDS_LOCATIONS = SimplecmdsLocations.SIMPLECMDS_LOCATIONS;

    /**
     * The table <code>simplecmds_warps</code>.
     */
    public static final SimplecmdsWarps SIMPLECMDS_WARPS = SimplecmdsWarps.SIMPLECMDS_WARPS;

    /**
     * The table <code>terrenos</code>.
     */
    public static final Terrenos TERRENOS = Terrenos.TERRENOS;

    /**
     * The table <code>terrenos_players</code>.
     */
    public static final TerrenosPlayers TERRENOS_PLAYERS = TerrenosPlayers.TERRENOS_PLAYERS;

    /**
     * The table <code>whitelistcmd</code>.
     */
    public static final Whitelistcmd WHITELISTCMD = Whitelistcmd.WHITELISTCMD;
}
