/*
 * This file is generated by jOOQ.
 */
package dev.feldmann.redstonegang.wire.game.base.addons.server.correio.db.tables.records;


import dev.feldmann.redstonegang.wire.game.base.addons.server.correio.db.tables.Correio;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record9;
import org.jooq.Row9;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CorreioRecord extends UpdatableRecordImpl<CorreioRecord> implements Record9<Long, Integer, Integer, String, Double, byte[], Boolean, Boolean, Timestamp> {

    private static final long serialVersionUID = 929215351;

    /**
     * Setter for <code>correio.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>correio.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>correio.remetente</code>.
     */
    public void setRemetente(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>correio.remetente</code>.
     */
    public Integer getRemetente() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>correio.destinatario</code>.
     */
    public void setDestinatario(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>correio.destinatario</code>.
     */
    public Integer getDestinatario() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>correio.mensagem</code>.
     */
    public void setMensagem(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>correio.mensagem</code>.
     */
    public String getMensagem() {
        return (String) get(3);
    }

    /**
     * Setter for <code>correio.coins</code>.
     */
    public void setCoins(Double value) {
        set(4, value);
    }

    /**
     * Getter for <code>correio.coins</code>.
     */
    public Double getCoins() {
        return (Double) get(4);
    }

    /**
     * Setter for <code>correio.itens</code>.
     */
    public void setItens(byte... value) {
        set(5, value);
    }

    /**
     * Getter for <code>correio.itens</code>.
     */
    public byte[] getItens() {
        return (byte[]) get(5);
    }

    /**
     * Setter for <code>correio.itenstrans</code>.
     */
    public void setItenstrans(Boolean value) {
        set(6, value);
    }

    /**
     * Getter for <code>correio.itenstrans</code>.
     */
    public Boolean getItenstrans() {
        return (Boolean) get(6);
    }

    /**
     * Setter for <code>correio.aberta</code>.
     */
    public void setAberta(Boolean value) {
        set(7, value);
    }

    /**
     * Getter for <code>correio.aberta</code>.
     */
    public Boolean getAberta() {
        return (Boolean) get(7);
    }

    /**
     * Setter for <code>correio.data</code>.
     */
    public void setData(Timestamp value) {
        set(8, value);
    }

    /**
     * Getter for <code>correio.data</code>.
     */
    public Timestamp getData() {
        return (Timestamp) get(8);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record9 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row9<Long, Integer, Integer, String, Double, byte[], Boolean, Boolean, Timestamp> fieldsRow() {
        return (Row9) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row9<Long, Integer, Integer, String, Double, byte[], Boolean, Boolean, Timestamp> valuesRow() {
        return (Row9) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return Correio.CORREIO.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return Correio.CORREIO.REMETENTE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return Correio.CORREIO.DESTINATARIO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return Correio.CORREIO.MENSAGEM;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Double> field5() {
        return Correio.CORREIO.COINS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<byte[]> field6() {
        return Correio.CORREIO.ITENS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field7() {
        return Correio.CORREIO.ITENSTRANS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field8() {
        return Correio.CORREIO.ABERTA;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field9() {
        return Correio.CORREIO.DATA;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component2() {
        return getRemetente();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component3() {
        return getDestinatario();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getMensagem();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double component5() {
        return getCoins();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public byte[] component6() {
        return getItens();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean component7() {
        return getItenstrans();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean component8() {
        return getAberta();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component9() {
        return getData();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getRemetente();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getDestinatario();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getMensagem();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double value5() {
        return getCoins();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public byte[] value6() {
        return getItens();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value7() {
        return getItenstrans();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value8() {
        return getAberta();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value9() {
        return getData();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CorreioRecord value1(Long value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CorreioRecord value2(Integer value) {
        setRemetente(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CorreioRecord value3(Integer value) {
        setDestinatario(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CorreioRecord value4(String value) {
        setMensagem(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CorreioRecord value5(Double value) {
        setCoins(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CorreioRecord value6(byte... value) {
        setItens(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CorreioRecord value7(Boolean value) {
        setItenstrans(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CorreioRecord value8(Boolean value) {
        setAberta(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CorreioRecord value9(Timestamp value) {
        setData(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CorreioRecord values(Long value1, Integer value2, Integer value3, String value4, Double value5, byte[] value6, Boolean value7, Boolean value8, Timestamp value9) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached CorreioRecord
     */
    public CorreioRecord() {
        super(Correio.CORREIO);
    }

    /**
     * Create a detached, initialised CorreioRecord
     */
    public CorreioRecord(Long id, Integer remetente, Integer destinatario, String mensagem, Double coins, byte[] itens, Boolean itenstrans, Boolean aberta, Timestamp data) {
        super(Correio.CORREIO);

        set(0, id);
        set(1, remetente);
        set(2, destinatario);
        set(3, mensagem);
        set(4, coins);
        set(5, itens);
        set(6, itenstrans);
        set(7, aberta);
        set(8, data);
    }
}
