/*
 * This file is generated by jOOQ.
 */
package dev.feldmann.redstonegang.wire.game.base.addons.server.quests.db;


import dev.feldmann.redstonegang.wire.game.base.addons.server.quests.db.tables.QuestInfos;
import dev.feldmann.redstonegang.wire.game.base.addons.server.quests.db.tables.Quests;
import dev.feldmann.redstonegang.wire.game.base.addons.server.quests.db.tables.records.QuestInfosRecord;
import dev.feldmann.redstonegang.wire.game.base.addons.server.quests.db.tables.records.QuestsRecord;

import javax.annotation.Generated;

import org.jooq.Identity;
import org.jooq.UniqueKey;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables of 
 * the <code></code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------

    public static final Identity<QuestsRecord, Integer> IDENTITY_QUESTS = Identities0.IDENTITY_QUESTS;
    public static final Identity<QuestInfosRecord, Integer> IDENTITY_QUEST_INFOS = Identities0.IDENTITY_QUEST_INFOS;

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<QuestsRecord> KEY_QUESTS_PRIMARY = UniqueKeys0.KEY_QUESTS_PRIMARY;
    public static final UniqueKey<QuestInfosRecord> KEY_QUEST_INFOS_PRIMARY = UniqueKeys0.KEY_QUEST_INFOS_PRIMARY;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Identities0 {
        public static Identity<QuestsRecord, Integer> IDENTITY_QUESTS = Internal.createIdentity(Quests.QUESTS, Quests.QUESTS.ID);
        public static Identity<QuestInfosRecord, Integer> IDENTITY_QUEST_INFOS = Internal.createIdentity(QuestInfos.QUEST_INFOS, QuestInfos.QUEST_INFOS.ID);
    }

    private static class UniqueKeys0 {
        public static final UniqueKey<QuestsRecord> KEY_QUESTS_PRIMARY = Internal.createUniqueKey(Quests.QUESTS, "KEY_quests_PRIMARY", Quests.QUESTS.ID);
        public static final UniqueKey<QuestInfosRecord> KEY_QUEST_INFOS_PRIMARY = Internal.createUniqueKey(QuestInfos.QUEST_INFOS, "KEY_quest_infos_PRIMARY", QuestInfos.QUEST_INFOS.ID);
    }
}
