/*
 * This file is generated by jOOQ.
 */
package dev.feldmann.redstonegang.wire.game.base.addons.server.quests.db;


import dev.feldmann.redstonegang.wire.game.base.addons.server.quests.db.tables.QuestInfos;
import dev.feldmann.redstonegang.wire.game.base.addons.server.quests.db.tables.Quests;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in 
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>quests</code>.
     */
    public static final Quests QUESTS = Quests.QUESTS;

    /**
     * The table <code>quest_infos</code>.
     */
    public static final QuestInfos QUEST_INFOS = QuestInfos.QUEST_INFOS;
}
