/*
 * This file is generated by jOOQ.
 */
package dev.feldmann.redstonegang.wire.game.base.database.addons.tables;


import dev.feldmann.redstonegang.wire.game.base.database.addons.DefaultSchema;
import dev.feldmann.redstonegang.wire.game.base.database.addons.Indexes;
import dev.feldmann.redstonegang.wire.game.base.database.addons.Keys;
import dev.feldmann.redstonegang.wire.game.base.database.addons.tables.records.SimplecmdsLocationsRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SimplecmdsLocations extends TableImpl<SimplecmdsLocationsRecord> {

    private static final long serialVersionUID = -1268069037;

    /**
     * The reference instance of <code>simplecmds_locations</code>
     */
    public static final SimplecmdsLocations SIMPLECMDS_LOCATIONS = new SimplecmdsLocations();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<SimplecmdsLocationsRecord> getRecordType() {
        return SimplecmdsLocationsRecord.class;
    }

    /**
     * The column <code>simplecmds_locations.id</code>.
     */
    public final TableField<SimplecmdsLocationsRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>simplecmds_locations.name</code>.
     */
    public final TableField<SimplecmdsLocationsRecord, String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR(64).nullable(false), this, "");

    /**
     * The column <code>simplecmds_locations.location</code>.
     */
    public final TableField<SimplecmdsLocationsRecord, String> LOCATION = createField("location", org.jooq.impl.SQLDataType.VARCHAR(255), this, "");

    /**
     * Create a <code>simplecmds_locations</code> table reference
     */
    public SimplecmdsLocations() {
        this(DSL.name("simplecmds_locations"), null);
    }

    /**
     * Create an aliased <code>simplecmds_locations</code> table reference
     */
    public SimplecmdsLocations(String alias) {
        this(DSL.name(alias), SIMPLECMDS_LOCATIONS);
    }

    /**
     * Create an aliased <code>simplecmds_locations</code> table reference
     */
    public SimplecmdsLocations(Name alias) {
        this(alias, SIMPLECMDS_LOCATIONS);
    }

    private SimplecmdsLocations(Name alias, Table<SimplecmdsLocationsRecord> aliased) {
        this(alias, aliased, null);
    }

    private SimplecmdsLocations(Name alias, Table<SimplecmdsLocationsRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> SimplecmdsLocations(Table<O> child, ForeignKey<O, SimplecmdsLocationsRecord> key) {
        super(child, key, SIMPLECMDS_LOCATIONS);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return DefaultSchema.DEFAULT_SCHEMA;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.SIMPLECMDS_LOCATIONS_NAME, Indexes.SIMPLECMDS_LOCATIONS_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<SimplecmdsLocationsRecord, Integer> getIdentity() {
        return Keys.IDENTITY_SIMPLECMDS_LOCATIONS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<SimplecmdsLocationsRecord> getPrimaryKey() {
        return Keys.KEY_SIMPLECMDS_LOCATIONS_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<SimplecmdsLocationsRecord>> getKeys() {
        return Arrays.<UniqueKey<SimplecmdsLocationsRecord>>asList(Keys.KEY_SIMPLECMDS_LOCATIONS_PRIMARY, Keys.KEY_SIMPLECMDS_LOCATIONS_NAME);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SimplecmdsLocations as(String alias) {
        return new SimplecmdsLocations(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SimplecmdsLocations as(Name alias) {
        return new SimplecmdsLocations(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public SimplecmdsLocations rename(String name) {
        return new SimplecmdsLocations(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public SimplecmdsLocations rename(Name name) {
        return new SimplecmdsLocations(name, null);
    }
}
